### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Wimmi7** [erbkaiser/FrozenCookies#101]
![error](https://user-images.githubusercontent.com/109187143/189510435-d0486b07-2d0b-4d42-af7c-99b5b6690ffa.PNG)
Game freezes on add-on load. Attached is the console output

**Comment by erbkaiser** [comment]
Thanks for the report. It will now properly load on a game that does not have the Grimoire unlocked yet again.

Fixed in https://github.com/erbkaiser/FrozenCookies/commit/246a9e02d5644092e4c430b2eb8ec4d582e01413
