### ISSUE TITLE
Autoascend spends time on the upgrade screen

### ISSUE THREAD

**Issue by ghost** [erbkaiser/FrozenCookies#106]
Autoascend says that it will skip the upgrade screen (which it does) but it spends about 5 seconds there first. Submitting this issue because it's unclear (to me) if this is a bug on my side, a bug in the code, or intended behavior for some reason (if so, couldn't find an explanation in the Readme or Issues here or on the original)
If possible, It would be nice for that time to be shortened

**Comment by erbkaiser** [comment]
That is normal behaviour. Actual time spent there depends on how fast the script can detect the upgrade screen has been fully loaded and run the next function. I will update the documentation to mention it.
