### ISSUE TITLE
Auto cast FTHoF never casts Click Frenzy

### ISSUE THREAD

**Issue by ghost** [erbkaiser/FrozenCookies#107]
The readme says that FTHOF will wait to cast Click Frenzy until something like Frenzy or Dragon Harvest is active. But I've had full mana, Frenzy, and Dragon Harvest all at the same time (with enough time to last all of Click Frenzy) and it didn't even cast at that point. I have autocast set to 1x Frenzy, so I wouldn't think that should screw with anything, and while I haven't had that multiple combo situation more than once (that I caught) I have seen it several times miss a Frenzy, Dragon Harvest, or a building special on their own.

**Comment by erbkaiser** [comment]
Hi,

the documention is not fully correct (yet). For a click frenzy, it will wait for a natural frenzy and/or Dragon Harvest but also a building special with at least the full click frenzy time remaining.

Does that explain what you are seeing?

**Comment by ghost** [comment]
I will have to wait and see. I think it missed one of those, but maybe the timing just wasn't quite correct. I'll try cheating those buffs in and seeing if that triggers it correctly, once I get back to my computer. Should I just test it in the browser, assuming the script is similar there, or since I normally play on steam should I also try it there?

**Comment by ghost** [comment]
Follow up: first, I was going to tell you that it didn't work with the opensesame spawned cookies, but I would update you when a genuine effect happened or if I tried cheating them in other ways. Then, right before I came here to say that, a natural frenzy and a building special happened (on Steam, not in the browser window I was testing the cheats in) and it still didn't cast the click frenzy. I personally cast the click frenzy and it only didn't overlap with the frenzy for a second, and since it took me at least a few seconds to realize what I was seeing, I'm sure there would have been plenty of time if it were cast more promptly by the code

**Comment by erbkaiser** [comment]
Thanks for testing. That's weird... I have it working myself right now.

To further narrow down the issue:
-Which autocast method are you using?
-What dragon auras (if any) are active?
-What is your wizard tower level and max mana?

**Comment by ghost** [comment]
-I'm just using normal auto cast
-I'm using Reaper of Fields and Dragonflight
-Level one, max mana 37

**Comment by erbkaiser** [comment]
Okay, that might explain it.
If Reaper of Fields is an active aura, it will require a Frenzy AND a Dragon Harvest & building special.
Without RoF, it will only require a frenzy OR dragon harvest (since DH is also possible with Reality Bending) & building special.

I'll update the documentation.
