### ISSUE TITLE
Question: Why does Auto Godzamok activate during Cursed Finger?

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#109]
From what I've been told from people on Discord, Cursed Finger apparently doesn't stack with Buffs, Godzamok, or even Golden Switch if they were done in the middle of the effect. CuF "locks in" how many cookies you get per click based on your cps when the effect activates, and any changes to click power or cps are lost until CuF ends. Maybe I'm missing something?

**Comment by erbkaiser** [comment]
I don't think that what you are told is correct. Looking at the game code there appears to be nothing that locks the effect in either the Cursed Finger buff or the devastation (Godz effect).

Granted, I have no idea where it DOES define what Cursed Finger does, exactly.
I can find where it sets CpS to 0 and where it applies Game.buffs['Cursed finger'].power to mouseCpS, but not where that power is defined.

Either way, it's inherited from upstream and I am not going to touch it before I understand what it does.

**Comment by erbkaiser** [comment]
So I finally got around to doing some testing on this. CF _on its own_ is indeed not worth enabling Godz for. I've now disabled it from triggering Godz if no other click buff is active.
