### ISSUE TITLE
100% consistency combo removes whiskerbloom to make room for whiskerbloom

### ISSUE THREAD

**Issue by scowdich** [erbkaiser/FrozenCookies#112]
I've witnessed the automatic consistency combo, when performing a double-cast, remove a field of immature whiskerbloom in order to plant brand-new whiskerbloom seeds. Would it be possible for the function to skip that step if the plants occupying the field are already correct (and more effective than brand-new plants)?

**Comment by erbkaiser** [comment]
It's correct that right now it will simply wipe the entire garden but it should be doable to scan it first, and leave it alone if it's already WB.
I'll experiment a bit to see if I can get this to work.
