### ISSUE TITLE
Auto-Godz and Auto-loans are not working.

### ISSUE THREAD

**Issue by windswell** [erbkaiser/FrozenCookies#115]
Auto-Godz and Auto-loans not working. Probably since Combo Cast was removed.

**Comment by erbkaiser** [comment]
Auto Godz should have been fixed since. Please reload and see if it works again. Loans I'm investigating.

**Comment by erbkaiser** [comment]
Found it, fix being pushed now.

**Comment by erbkaiser** [comment]
Fixed with https://github.com/erbkaiser/FrozenCookies/commit/c2e67895d7297f5362d6ca62943c8af5f00f8b75
