### ISSUE TITLE
Add an enhancement that sorts upgrades and buildings based off of what the next best thing to buy is

### ISSUE THREAD

**Issue by zuils** [erbkaiser/FrozenCookies#117]
It be cool to do that.

**Comment by erbkaiser** [comment]
You can already find that info on the Frozen Cookies settings page under Internal Information.

Doing it in the panels is not something that is easy to implement and IMO provides little value to Frozen Cookies itself, which is essentially all about automation. Mods like Cookie Monster have this, and those are intended to just provide info on what to buy yourself next, not automating anything.
