### ISSUE TITLE
Can't Get FrozenCookie to work

### ISSUE THREAD

**Issue by Hubezz** [erbkaiser/FrozenCookies#119]
I have cookie clicker on steam and wanted to automate some of the tedious buying and upgrading. I tried a few other mods but this one seems the most promising. only thing is though is that I cant get it to work :/. I subscribed to it on steam Workshop and loaded the game but it didn't work. I deleted and unsubscribed to all the all other mods I had and that didn't work. I followed the steps on the Steam Workshop page and still no luck. is there something i can do to make this mod work?

**Comment by erbkaiser** [comment]
If you go to Options > Manage Mods, is Frozen Cookies listed? If not, then your Steam is not downloading it for some reason.

With Cookie Clicker closed, unsubscribe from Frozen Cookies on the workshop. Open CC, and close it again. Then resubscribe.

If this STILL does not work:
-In the Manage mods window again, go to Open /mods folder
-Go to local
-Create a folder named FrozenCookies
-Download [info.txt and main.js from the Github](https://github.com/erbkaiser/FrozenCookies/tree/main/Steam/FrozenCookies) to that folder
-Close and reopen CC
-Go to Manage Mods and now FrozenCookies should appear.

**Comment by Hubezz** [comment]
So I tried this as well but still no luck. I can see the mod show up when I go to the Manage Mods in the options but Noting happens when I enable the Mod. I tried using some of the hotkeys I saw in the ReadMe File but I'm but seeing any sort of feed back form the Mod

**Comment by erbkaiser** [comment]
If the mod is enabled and Cookie Clicker is reloaded, the Info button should become the Frozen Cookies button. 
If you see that, it's working. Go to the bottom of that menu and enable Recommended settings, or pick your own. 

If the button does not appear, no idea.

**Comment by Hubezz** [comment]
I'm an Idiot, Thank you so much! Never noticed that botton
