### ISSUE TITLE
I'm not using Godzamok but seems like last update borked other things too.

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#122]
I'm not using Godzamok but seems like last update borked other things too.
First I noticed wrinklers were not popped and all my wizard towers were sold, then I realized the whole app looks like peg down by some infinite loop somewhere, slow responding, can barely click anything and... not doing anything. Basically nothing works for me now.
When ascending it buys few cursors and then stops like described above.

_Originally posted by @mg-pl in https://github.com/erbkaiser/FrozenCookies/issues/121#issuecomment-1446465627_

**Comment by erbkaiser** [comment]
> @erbkaiser: @mg-pl please write down your current FC settings, then use the **Recommended** at the bottom of the options window. This will reset FC, after which hopefully it will work and you can set your desired options again.

> @mg-pl: Seems like i had AutoBuy off, not sure how that happened. Anyway, now it's doing something but the (web)app remained hardly responsive.

> @erbkaiser: Most combos (temporarily) turn off AutoBuy. If anything goes wrong there, it breaks. I have tried to put in some catches on reloading, but it does not always work.

**Comment by mg-pl** [comment]
Something is definitely different, see the gif with stuttering recorded. It looks like that regardless of the FPS setting.
![fc](https://user-images.githubusercontent.com/92392582/221650250-ade36f14-f9c6-445c-8328-e64c474e0d46.gif)

**Comment by erbkaiser** [comment]
The excessive stuttering should be fixed by the last few updates. If not, please let me know.
