### ISSUE TITLE
Config Options for FTHOF Auto Cast and Radial Info Display

### ISSUE THREAD

**Issue by jakj** [erbkaiser/FrozenCookies#123]
Request for FTHOF auto-cast: Option to not wait for extra conditions on simple FTHOF auto-cast, but instead just auto-cast whenever the specified frenzy is active. (Regardless of optimality, I am not liking that it won't use FTHOF when it's "just" a simple x7 frenzy.)

Request for radial info display below the cookie: Option to not have the bank mixed with the next item to purchase. (If saving for bank, should just be gold ring indicating how much of the bank is filled; If not saving for bank, should just be black circle indicating progress of current purchase alone, not in addition to the bank. It's misleading/distracting to see a black circle nearly full when the bulk of the circle is just the bank.)

**Comment by erbkaiser** [comment]
Since the beta might be coming out any time now, I am going to explore this further after it goes live.

**Comment by erbkaiser** [comment]
Auto Cast changes will be implemented in version 2.05
Radial menu is under investigation.

**Comment by erbkaiser** [comment]
Autocast changes are live.
I can't edit the radial menu code, unfortunately.
