### ISSUE TITLE
Holobore not being slotted by auto-Pantheon

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#131]
Reported here https://github.com/erbkaiser/FrozenCookies/commit/b765cf7c16ee061f3a386f56a3a9f59f9fdd8b4f#commitcomment-104436673

**Comment by erbkaiser** [comment]
@Hringingy are you saying this does work in live, but not in the beta?

**Comment by Hringingy** [comment]
I first saw this in the beta version, but after testing it also seems to be happening in the live version too

**Comment by erbkaiser** [comment]
I can't get this to work. Removing Holobore as an option.
