### ISSUE TITLE
Auto buy/auto clicker stops when changing bulk buy amount and attempting to purchase Wizard Tower

### ISSUE THREAD

**Issue by fesoliveira014** [erbkaiser/FrozenCookies#132]
Hey, I am playing at the v2.048 on Steam, and after Ascending, if I change the bulk buy amount (in CC, not FC) once it gets to a point where the next purchase is a Wizard Tower, FC gets stuck and stops auto-buying and auto-clicking. The only active mods I have are FC and Steam Achievement Unlocker.

**Comment by erbkaiser** [comment]
I cannot reproduce this. Can you provide some more info, such as exactly what your bulk mode is before and after?

**Comment by erbkaiser** [comment]
Closing due to lack of info.
