### ISSUE TITLE
Raw Cookies Per Second during this Ascension Error

### ISSUE THREAD

**Issue by skyethepinkcat** [erbkaiser/FrozenCookies#133]
So, from what I can tell, this happens whenever I load my game with FrozenCookies. I'm not sure why -- it may be that I'm missing a setting -- but the highest raw cookies per second during this ascension skyrockets to over 300 quadrillion, when it probably shouldn't be more than 1 billion since I'm pretty early in the run.

**Comment by erbkaiser** [comment]
This is a known issue that I unfortunately cannot solve. My best guess is that it is a result of the efficiency calculations.

See #19
