### ISSUE TITLE
auto cast FTHOF buys haggler charm on steam version

### ISSUE THREAD

**Issue by TylorBane** [erbkaiser/FrozenCookies#138]
not sure what i can say here, been this way for as long as i can remember, only reason i'm bringing it up now is i started playing again now that frozen is compatible with ccse, any time i turn on auto casting for FTHOF it never actually does it, only makes upgrades cheaper instead
not sure what i can do to prove it or show evidence, so let me know how i can be of any help

**Comment by erbkaiser** [comment]
Check the readme to see if it explains your scenario. Every auto-cast method except for FTHOF simple will skip certain spells.
If that doesn't help, let me know what your active auto-cast method is, what your Wizard Tower level is, and how much your mana is at.

Can you perhaps also try it without CCSE? I don't use it myself and it's possible it somehow interferes with the grimoire.

**Comment by TylorBane** [comment]
i seeeeee, so if i just want it to spam fthof without doing anything i have to use simple, every other option for fthof has a complex set of what to do first, apologies, i was unaware and that's probably what's going on, i'll watch it for a while and see what it's doing, you can go ahead and close this if you'd like, apologies again

**Comment by erbkaiser** [comment]
No problem, glad you figured it out.
The various auto casting methods can be a bit complex, I did my best to document them but it is a big change from how the 'official' Frozen Cookies works, which only has what I call 'simple'.
