### ISSUE TITLE
frozen cookies outputting 100 errors and lagging out cookie clicker.

### ISSUE THREAD

**Issue by NEILASc** [erbkaiser/FrozenCookies#145]
![image](https://github.com/erbkaiser/FrozenCookies/assets/81015613/c361c105-8b03-496d-abc8-5f124369ff11)

if you wanna reproduce, just load up (with or without monster cookies) and frozen cookies. the image below is without monster cookies:

![image](https://github.com/erbkaiser/FrozenCookies/assets/81015613/a8855036-e577-4efb-9e27-bb1fda2ebf78)

and atleast 5-4 errors per second. please fix lol

**Comment by erbkaiser** [comment]
I have no interest in troubleshooting console errors, especially not if they only occur when used with other mods.

**Comment by Blastinburn** [comment]
> I have no interest in troubleshooting console errors, especially not if they only occur when used with other mods.

I also have this issue and want to clarify a few points.  The issue isn't just console errors but the game being unplayable, either lagging out so much that it can't be played or flat out freezing.  Second, the errors occur without other mods, the first screenshot the game will lag out with only frozen cookies active.  The errors are different when cookie monster is installed which seems notable, but the problem does occur without other mods.

**Comment by erbkaiser** [comment]
The errors are inherited from upstream and I don't feel like spending time debugging them as the mod works well enough. If anyone else feels like tackling them, I welcome pull requests.
