### ISSUE TITLE
Auto Ascend at X heavenly chips is not working

### ISSUE THREAD

**Issue by leftbones** [erbkaiser/FrozenCookies#147]
It might be because the game is pretty laggy whenever I have autobuy turned on, but it seems that regardless of what I have the heavenly chips goal set to, if that number is missed, auto ascend never happens.

Setting it to 1 should ascend if the number of heavenly chips is >= 1, ideally

**Comment by leftbones** [comment]
Okay... setting "Ascend during combo" to ON fixed the problem? No idea why, I was just messing with settings...

**Comment by erbkaiser** [comment]
I cannot reproduce this, if there is no CpS boost active and I have it set for any value, it will use it.

If 'during Combo' is NOT checked, it will not ascend with one active, that is by design.
