### ISSUE TITLE
take `AutoClick: OFF` into account when calculating `actualCps`

### ISSUE THREAD

**Issue by nebocco** [erbkaiser/FrozenCookies#151]
Since `AutoClick` ON/OFF is not taken into account when calculating `actualCps`, turning `AutoClick` OFF with a large value in `AutoClick` will result in extremely slow progress in `Time til completion`. This was especially noticeable immediately after ascending, and in some cases it took more than 3 seconds for `Time til completion` to decrease by 1s.
Therefore, I propose to modify the following line;

https://github.com/erbkaiser/FrozenCookies/blob/54b9d894b6bd05422e9f9f3afe4e32ec7dfcc23f/fc_button.js#L312

to

```js
actualCps = Game.cookiesPs + Game.mouseCps() * FrozenCookies.cookieClickSpeed * FrozenCookies.autoClick
```

like
https://github.com/erbkaiser/FrozenCookies/blob/54b9d894b6bd05422e9f9f3afe4e32ec7dfcc23f/fc_button.js#L690-L692

**Comment by erbkaiser** [comment]
Good call, implemented
