### ISSUE TITLE
Partially disabling certain steps in the 100% efficiency combo

### ISSUE THREAD

**Issue by be5invis** [erbkaiser/FrozenCookies#152]
I am wondering whether it is possible to _partially_ disable some of the steps in the 100% efficiency combo, since some of the prerequisites (like the garden req) may be hard to unlock.

Examples:

 * Disable the garden step if Whiskerblooms are not unlocked.
 * Disable 3rd and 4th FTHOF casting if there's no sugar lump reserve.
 * Activate the "Sugar frenzy" switch if there are more SL reserves and this switch is enabled.

We could even go further to activate these addtional buffing steps for double casting FTHOF combos too, so the player will not need to wait for too long to get a large boost.

**Comment by erbkaiser** [comment]
With those changes, you basically end up with the existing Double Cast FTHOF combo.
