### ISSUE TITLE
Autobuy randomly breaks when wizard tower not unlocked

### ISSUE THREAD

**Issue by azy2** [erbkaiser/FrozenCookies#153]
If autobuy is left to run for a while it will sometimes fail with this message.
```
Uncaught TypeError: M is undefined
    autoCookie https://github.erbkaiser.com/FrozenCookies//fc_main.js?_=1702872680343:5800
fc_main.js:5800:36
    autoCookie https://github.erbkaiser.com/FrozenCookies//fc_main.js?_=1702872680343:5800
```
Digging into the code briefly it looks like M represents the wizard tower minigame which I do not have unlocked yet. Perhaps a nullcheck is needed here.

**Comment by erbkaiser** [comment]
Thanks for the report, should be fixed by the linked commit. I have let a new CC run until I unlocked WTs and the error did not occur.
