### ISSUE TITLE
Frozen Cookies can make Neverclick impossible

### ISSUE THREAD

**Issue by Patashu** [erbkaiser/FrozenCookies#157]
I reproduced it on both Steam and web.

Use this savefile:

`Mi4wNTJ8fDE3MDYwNTQ3MDc2NjM7MTcwNTU1ODU4OTUxNTsxNzA2MDU0NzQ0MzQ4O1BhdGFzaHU7anFvaHM7MCwxLDAsMCwwLDAsMHwwMDExMTAwMTEwMDEwMDEwMDExMTAxMTAwMDF8MS41NTMzMzMzMzMzMzMzNDIxOzE2LjU1MzMzMzMzMzMzMzU3NjsxNTsyMDQwOzE1OzY0OzIzOzg7MS40MTA3NTA4MDI0MjQ1NTYyZSs1OTswOzA7MDswOzA7MTA5OzA7MDswOzA7MDswOzA7OzA7MDs1MjA1NzUxNTI4NjM1NjAyOzcwODY4NTQwMjI3MzU1NDs0NDk3MDY2MTI2MzYyMDQ4OzA7MTs1Mjs1Mzs0NjI7NDk0OzYxMzswOzA7MDs0OzA7MDswOzA7NDsxNzA2MDM2NDY5MDQ1OzA7Mzs7MTAwOzA7MDswLjE7MDs4OTI7ODkyO3wxLDEsMCwwLCwwLDE7MCwwLDAsMCwsMSwwOzAsMCwwLDEsMTcwNjA1NDcwNzY2OTowOjE3MDYwNTQ3MDc2Njk6MDowOjQ0OjA6MDoxNzA2MDU0NzA3NjY5OiAxMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwLDA7MCwwLDAsMCwsMSwwOzAsMCwwLDAsLDEsMDswLDAsMCwxLDA6MDoxOjA6MDogMTY0NDoxOjIzOjQwNzowOjE6MDowITU2MTI6Mzo4NjoyNzowOjE6MDowITI4MzE6MjoxMDoxNjc6MDoxOjA6MCE0Nzk2OjA6ODI6NDUyOjA6MTowOjAhNTIwODoxOjk1Ojg3OjA6MTowOjAhNTIxNzo1OjEwOjUyNDowOjE6MDowITY4OTQ6MTo4OjIxMDowOjE6MDowITc1Mzg6MToxMDoyMDc6MDoxOjA6MCE4OTE2OjI6LTE1OjE4NjowOjE6MDowITgwODk6NTo5Mzo1NzY6MDoxOjA6MCExMTE5NjoyOjQ3OjQwOTowOjE6MDowITEyMjcwOjE6MTY6Mzc2OjA6MTowOjAhMTMyMjI6MTo3OjI4MTowOjE6MDowITE0OTE2OjE6NTk6NTY5OjA6MTowOjAhMTcyNjc6Mzo0OTozOTg6MDoxOjA6MCExNjM3NjoyOi05OjUyNzowOjE6MDowITE3MjY0OjU6OTozNjg6MDoxOjA6MCExNzgzMTowOjE6MjQ3OjA6MTowOjAhIDAsMCwwOzAsMCwwLDEsLTEvLTEvLTEgMyAxNzA2MDU0NzA3NjcxIDAsMCwwOzAsMCwwLDEsNSAwIDg3IDAsMCwwOzAsMCwwLDAsLDEsMDswLDAsMCwwLCwxLDA7MCwwLDAsMCwsMSwwOzAsMCwwLDAsLDEsMDswLDAsMCwwLCwxLDA7MCwwLDAsMCwsMSwwOzAsMCwwLDAsLDEsMDswLDAsMCwwLCwxLDA7MCwwLDAsMCwsMSwwOzAsMCwwLDAsLDEsMDswLDAsMCwwLCwxLDA7MCwwLDAsMCwsMSwwO3wxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMDEwMTEwMDExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTAwMTExMTExMTEwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMTExMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAxMDEwMTAxMDExMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTAxMTExMTEwMTExMTExMDExMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDEwMDAxMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTAwMDAwMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTEwMDAwMDAwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTAxMTExMDExMTAwMDAxMTExMTExMTExMTEwMDExMTAxMTExMTExMTExMTExMTEwMDAxMDExMDAxMTExMDAwMDExMDAwMDExMTAxMDExMTExMTExMTExMDAwMTExMDExMTExMTExMTExMTAwMDAwMDAwMDExMTB8fGZyb3plbl9jb29raWVzOnsiY2xpY2tpbmdPcHRpb25zIjowLCJhdXRvQ2xpY2siOjAsImF1dG9GcmVuenkiOjAsImF1dG9HQyI6MSwiYXV0b1JlaW5kZWVyIjoxLCJhdXRvRm9ydHVuZSI6MSwiYnV5aW5nT3B0aW9ucyI6MCwiYXV0b0J1eSI6MSwib3RoZXJVcGdyYWRlcyI6MSwiYXV0b0JsYWNrbGlzdE9mZiI6MCwiYmxhY2tsaXN0IjowLCJtaW5lTGltaXQiOjEsImZhY3RvcnlMaW1pdCI6MSwicGFzdGVtb2RlIjowLCJhdXRvT3RoZXJPcHRpb25zIjowLCJhdXRvQnVsayI6MiwiYXV0b0J1eUFsbCI6MSwiYXV0b0FzY2VuZFRvZ2dsZSI6MCwiYXV0b0FzY2VuZCI6MSwiY29tYm9Bc2NlbmQiOjEsImF1dG9Xcmlua2xlciI6MSwic2hpbnlQb3AiOjAsImF1dG9TTCI6MSwiZHJhZ29uc0N1cnZlIjoyLCJzdWdhckJha2luZ0d1YXJkIjoxLCJhdXRvR1MiOjEsImF1dG9Hb2R6YW1vayI6MSwiYXV0b0JhbmsiOjAsImF1dG9Ccm9rZXIiOjAsImF1dG9Mb2FuIjoxLCJ3b3JzaGlwT3B0aW9ucyI6MCwiYXV0b1dvcnNoaXBUb2dnbGUiOjEsImF1dG9Xb3JzaGlwMCI6MiwiYXV0b1dvcnNoaXAxIjo4LCJhdXRvV29yc2hpcDIiOjYsImF1dG9DeWNsaXVzIjowLCJzcGVsbE9wdGlvbnMiOjAsInRvd2VyTGltaXQiOjEsImF1dG9DYXN0aW5nIjoyLCJzcGVsbE5vdGVzIjowLCJhdXRvRlRIT0ZDb21ibyI6MCwiYXV0bzEwMENvbnNpc3RlbmN5Q29tYm8iOjAsImF1dG9TdWdhckZyZW56eSI6MCwiYXV0b1N3ZWV0IjowLCJkcmFnb25PcHRpb25zIjowLCJhdXRvRHJhZ29uIjoxLCJwZXREcmFnb24iOjEsImF1dG9EcmFnb25Ub2dnbGUiOjAsImRyYWdvbk5vdGVzIjowLCJhdXRvRHJhZ29uQXVyYTAiOjE3LCJhdXRvRHJhZ29uQXVyYTEiOjE4LCJhdXRvRHJhZ29uT3JicyI6MCwib3JiTGltaXQiOjEsInNlYXNvbk9wdGlvbnMiOjAsImRlZmF1bHRTZWFzb25Ub2dnbGUiOjEsImRlZmF1bHRTZWFzb24iOjEsImZyZWVTZWFzb24iOjEsImF1dG9FYXN0ZXIiOjEsImF1dG9IYWxsb3dlZW4iOjEsImJhbmtPcHRpb25zIjowLCJob2xkU0VCYW5rIjowLCJzZXRIYXJ2ZXN0QmFua1BsYW50IjowLCJzZXRIYXJ2ZXN0QmFua1R5cGUiOjAsIm90aGVyT3B0aW9ucyI6MCwiRkNzaG9ydGN1dHMiOjEsInNpbXVsYXRlZEdDUGVyY2VudCI6MSwiZGlzcGxheU9wdGlvbnMiOjAsInNob3dNaXNzZWRDb29raWVzIjowLCJudW1iZXJEaXNwbGF5IjoxLCJmYW5jeXVpIjowLCJsb2dnaW5nIjowLCJwdXJjaGFzZUxvZyI6MCwic2xvd09wdGlvbnMiOjAsImZwc01vZGlmaWVyIjoyLCJ0cmFja1N0YXRzIjowLCJyZWNvbW1lbmRlZFNldHRpbmdzIjowLCJmcmVuenlDbGlja1NwZWVkIjoyMCwiY29va2llQ2xpY2tTcGVlZCI6MjAsIkhDQXNjZW5kQW1vdW50IjoxLCJtaW5lTWF4Ijo2MDAsImZhY3RvcnlNYXgiOjYwMCwibWluQ3BTTXVsdCI6NDAwLCJtaW5Mb2FuTXVsdCI6Nzc3LCJtaW5BU0ZNdWx0Ijo3Nzc3LCJmcmVuenlUaW1lcyI6Int9IiwibGFzdEhDQW1vdW50Ijo1MjA1NzUxNTI4NjM1NjAyLCJtYXhIQ1BlcmNlbnQiOjAsImxhc3RIQ1RpbWUiOjE3MDYwNTQ2MzEwMjgsIm1hbmFNYXgiOjM3LCJtYXhTcGVjaWFscyI6MSwib3JiTWF4Ijo0MDAsInByZXZMYXN0SENUaW1lIjoxNzA2MDU0NjMxMDI4LCJzYXZlVmVyc2lvbiI6IjIuMDUyLjQifTtNRVRBOipjb29sZXIgc2FtcGxlIG1vZCwqbGFuZyBzYW1wbGUgbW9kLCpzYW1wbGUgbW9kLCpmcm96ZW5fY29va2llczs%3D%21END%21`

1) Enable Frozen Cookies mod.

2) Ascend and reincarnate into Born Again.

2) Click the cookie 15 times. You'll actually generate 14.7 cookies.

I'm not sure what in FC eats the remaining 0.3 cookies.

**Comment by erbkaiser** [comment]
I think that the fix for #158 somehow also fixed this, since I can no longer reproduce it now whereas I could before.
I have no idea what might have been the actual cause.
Can you test again with the latest update to FC?

**Comment by Patashu** [comment]
Yeah I thought about it later, it wouldn't surprise me if they're the same issue (FC buys an upgrade by surprise that costs about 0.3 cookies). Thanks for investigating these! I'll let you know if I see the bug happen again.

**Comment by Patashu** [comment]
Yeah, whatever you changed, Neverclick now works OK.

**Comment by erbkaiser** [comment]
Great, thanks.
