### ISSUE TITLE
Frozen Cookies crashing when loaded

### ISSUE THREAD

**Issue by Patashu** [erbkaiser/FrozenCookies#160]
This savefile:

`Mi4wNTJ8fDE3MDY0MDUyNzExMjM7MTcwNTU1ODU4OTUxNTsxNzA2NTc5ODY5MzAwO1BhdGFzaHU7dW5zeWg7MTUsMTEsOCwwLDYsMTYsMjF8MDAxMTEwMDAxMDAxMDAxMDAxMTEwMTEwMDAxfDMuMzUyMjY3MzMwMzcxOTEwM2UrNjk7Ni44MzYyMzQ5ODAwMjQzMzJlKzY5OzIzNzk4NDk7NDc3Njs2LjgzNjA3MjE5NjY0NjZlKzY5OzY3OzIzOzMyOzEuMzgyMTM2MjU1MDgxOTgyNGUrNzA7MDs2OzA7MDstMTsxMTM7ODg1OzEuMjYzODc4NDExOTc1NjE2MmUrNTg7NTA7MTQ7MzA7MTE0NjI3Mzs4O2Zvb2xzOzA7MDsyMzk5ODQ3MzYwMTMxNDIyNjAwMDsyMzkyMjExMTg0MzUwMDMwMDAwMDs3NDkzODE0NTA2NDY0NzYwMDswOzA7ODcxOzg3MDs4NTg7NzY3Ozg3MjsyNzsxNTsxOzQ7MDswOzA7MDsxNDsxNzA2NTY2NTE3NzMwOzA7MDs7NDE7MTsxOzguNzI2NTUyNjI0Njc4NzczZSs1NzswOzg5Mjs4OTI7fDEwOTcsMTQ0NywxLjU3OTE3OTM4NDE1NDY4NTNlKzY0LDAsLDAsMTA5NzsxMDg3LDE0MzcsMS4xODEyMTQ2NzgyNjAyNzY1ZSs2MywwLCwxLDEwODc7MTA1NCwxNDA0LDEuNzAwMzA4MDY3NTM0MDA4M2UrNjMsNCwxNzA2NTgwMDM2MzQ3OjE6MTcwNjQwNjAxMTM4NTowOjQ2NDo5Mzk6MTowOjE3MDY0MDUyNzExMzM6IDExMTExMDExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjE6MjI6MToyMzoxOjIzOjE6MjM6MDowOjA6MDoxOjI1OjE6MjU6MToyMToxOjIzOjA6MDowOjA6MToyNDoxOjIzOjE6MjU6MToyMzowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6LDAsMTA1NDs5MDAsOTU1MDAsMy42NzM0OTkwMTY4NTUxNjQ1ZSs2MywwLCwxLDkwMDs5MDAsOTU1MDAsMy44MTY3MjU2NDg5MDg1Mjc1ZSs2MiwwLCwxLDkwMDs5OTAsMTM0MCw0LjQ1OTM1OTAxODM5OTEyNGUrNjEsMSwwOjA6MTowOjE6IDg1ODk6MjotMTAwOjQ2NDowOjA6MDowITU4NjE6MzotNDY6NTg3OjA6MDowOjAhODM0NToyOi01NDo2OTU6MDowOjA6MCE4MDc4OjI6LTI4Nzo1MDQ6MDowOjA6MCEyMDAwOjE6LTc6NzA6MDowOjA6MCE5NzI0OjU6LTEwMToyNTM6MDowOjA6MCE2NjMxOjE6LTE4Nzo0MTowOjA6MDowITk3OTg6MTotMjExOjY3MDowOjA6MDowITk3NzA6MjotMzYzOjQ5OjA6MDowOjAhOTg4MTo0Oi0zMTA6MjgxOjA6MDowOjAhOTEwMDowOi0yNjI6MTMxOjA6MDowOjAhMTQyMTI6MTotMjI5OjY2MTowOjA6MDowITkwNjY6NTo4NTo2MzM6MDowOjA6MCExMTYzNzo0Oi0xNTA6MzMyOjA6MDowOjAhMTY5NTM6MTotNjM6MTQ2OjA6MDowOjAhMTY5OTI6MjotMjIzOjQ2OjA6MDowOjAhMTgxMTM6MjotODA6NTg1OjA6MDowOjAhMjUzMzQ6NTo4NDo0ODY6MDowOjA6MCEgMSwxLDk5MDs5ODUsMTMzNiw0Ljk3NjY0ODE2OTkyMTQ4NWUrNjMsMSwyLzgvNiAzIDE3MDY0OTc4MzMxOTEgMCwxLDk4NTs1MTMsMzM3OCwxLjAwMDUwMjU4NDE5NDA2M2UrNjEsMSw5OSAyMjIgNzE3IDEsMCw3MTM7OTQ3LDEyOTcsMi40MjMwNDU2OTk0NDE1OTI2ZSs2MCwwLCwxLDk0Nzs5MTgsMTI2OCw2LjcxNjE0NjE1NTM0OTQyMWUrNjAsMCwsMSw5MTg7OTA2LDEyNTYsMS4yNTE1MDI3OTIzODkwOTk5ZSs2MywwLCwxLDkwNjs4OTMsMTI0MywzLjkzOTE2MTIyNDc2ODk1MWUrNjMsMCwsMSw4OTM7ODY3LDEyMTcsNy41NjEyNjc3MTY0MzAwNDJlKzYyLDAsLDEsODY3Ozg1NCwxMjA0LDIuMDYxNTY5NDg4Nzk4MDA4NGUrNjMsMCwsMSw4NTQ7ODM4LDExODgsMi41MjY0MDM4NDkzODI1Njc3ZSs2MywwLCwxLDgzODs4MjIsMTE3Miw5LjgyMTkwOTMyNTE4NTEyZSs2MywwLCwxLDgyMjs3ODgsMTEzOCwzLjMwMjM2MTk0NTgwNThlKzY0LDAsLDEsNzg4Ozc0MywxMDkzLDMuMTI3Nzc5ODUzMjExOTg2ZSs2MywwLCwxLDc0Mzs3MDksMTA1OSwxLjM1MjI0NzAwNjA5NzQ0N2UrNjQsMCwsMSw3MDk7Njg3LDEwNDIsNC4yMDEwOTA4MDAwNzMxNTk0ZSs2NCwwLCwxLDY4Nzt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTEwMDExMTExMTAwMTExMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTEwMTExMTExMDExMTExMTExMTAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMDAwMDExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTAxMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTEwMDExMTExfHxmcm96ZW5fY29va2llczp7ImNsaWNraW5nT3B0aW9ucyI6MCwiYXV0b0NsaWNrIjoxLCJhdXRvRnJlbnp5IjoxLCJhdXRvR0MiOjEsImF1dG9SZWluZGVlciI6MSwiYXV0b0ZvcnR1bmUiOjEsImJ1eWluZ09wdGlvbnMiOjAsImF1dG9CdXkiOjAsIm90aGVyVXBncmFkZXMiOjAsImF1dG9CbGFja2xpc3RPZmYiOjAsImJsYWNrbGlzdCI6MCwibWluZUxpbWl0IjoxLCJmYWN0b3J5TGltaXQiOjEsInBhc3RlbW9kZSI6MCwiYXV0b090aGVyT3B0aW9ucyI6MCwiYXV0b0J1bGsiOjIsImF1dG9CdXlBbGwiOjEsImF1dG9Bc2NlbmRUb2dnbGUiOjAsImF1dG9Bc2NlbmQiOjEsImNvbWJvQXNjZW5kIjoxLCJhdXRvV3JpbmtsZXIiOjEsInNoaW55UG9wIjowLCJhdXRvU0wiOjEsImRyYWdvbnNDdXJ2ZSI6Miwic3VnYXJCYWtpbmdHdWFyZCI6MSwiYXV0b0dTIjoxLCJhdXRvR29kemFtb2siOjEsImF1dG9CYW5rIjowLCJhdXRvQnJva2VyIjowLCJhdXRvTG9hbiI6MSwid29yc2hpcE9wdGlvbnMiOjAsImF1dG9Xb3JzaGlwVG9nZ2xlIjowLCJhdXRvV29yc2hpcDAiOjIsImF1dG9Xb3JzaGlwMSI6OCwiYXV0b1dvcnNoaXAyIjo2LCJhdXRvQ3ljbGl1cyI6MCwic3BlbGxPcHRpb25zIjowLCJ0b3dlckxpbWl0IjoxLCJhdXRvQ2FzdGluZyI6MCwic3BlbGxOb3RlcyI6MCwiYXV0b0ZUSE9GQ29tYm8iOjEsImF1dG8xMDBDb25zaXN0ZW5jeUNvbWJvIjowLCJhdXRvU3VnYXJGcmVuenkiOjAsImF1dG9Td2VldCI6MCwiZHJhZ29uT3B0aW9ucyI6MCwiYXV0b0RyYWdvbiI6MSwicGV0RHJhZ29uIjoxLCJhdXRvRHJhZ29uVG9nZ2xlIjowLCJkcmFnb25Ob3RlcyI6MCwiYXV0b0RyYWdvbkF1cmEwIjoxLCJhdXRvRHJhZ29uQXVyYTEiOjE1LCJhdXRvRHJhZ29uT3JicyI6MCwib3JiTGltaXQiOjAsInNlYXNvbk9wdGlvbnMiOjAsImRlZmF1bHRTZWFzb25Ub2dnbGUiOjEsImRlZmF1bHRTZWFzb24iOjEsImZyZWVTZWFzb24iOjEsImF1dG9FYXN0ZXIiOjEsImF1dG9IYWxsb3dlZW4iOjEsImJhbmtPcHRpb25zIjowLCJob2xkU0VCYW5rIjowLCJzZXRIYXJ2ZXN0QmFua1BsYW50IjowLCJzZXRIYXJ2ZXN0QmFua1R5cGUiOjAsIm90aGVyT3B0aW9ucyI6MCwiRkNzaG9ydGN1dHMiOjEsInNpbXVsYXRlZEdDUGVyY2VudCI6MSwiZGlzcGxheU9wdGlvbnMiOjAsInNob3dNaXNzZWRDb29raWVzIjowLCJudW1iZXJEaXNwbGF5IjoxLCJmYW5jeXVpIjowLCJsb2dnaW5nIjowLCJwdXJjaGFzZUxvZyI6MCwic2xvd09wdGlvbnMiOjAsImZwc01vZGlmaWVyIjoyLCJ0cmFja1N0YXRzIjowLCJyZWNvbW1lbmRlZFNldHRpbmdzIjowLCJmcmVuenlDbGlja1NwZWVkIjoyMCwiY29va2llQ2xpY2tTcGVlZCI6MjAsIkhDQXNjZW5kQW1vdW50IjoxLCJtaW5lTWF4Ijo5MDAsImZhY3RvcnlNYXgiOjkwMCwibWluQ3BTTXVsdCI6MzAwLCJtaW5Mb2FuTXVsdCI6Nzc3NywibWluQVNGTXVsdCI6Nzc3NywiZnJlbnp5VGltZXMiOiJ7XCIxXCI6MzQ4NzMyNTMsXCI3XCI6OTIxOTQ4MjUsXCI4NlwiOjE4Mzg2MCxcIjkxXCI6MzI2NDk2LFwiMTAwXCI6NjgwNjMsXCI2MDJcIjoyMDI4NSxcIjYzN1wiOjIxODgyMCxcIjcwMFwiOjY4MDcxLFwiNzc3XCI6NjYwOTIzLFwiNDY2MlwiOjE0MDcwLFwiNTQzOVwiOjI3MDQ5MixcIjYyLjdcIjozNDA3MCxcIjU1LjhcIjo2ODA2NCxcIjg4LjJcIjo2ODEwMCxcIjc2LjRcIjo2NTc0NCxcIjQzMS45MDAwMDAwMDAwMDAwM1wiOjU3NDI4LFwiNjEuN1wiOjEwNjQ3LFwiNjM4LjRcIjozNzk3MixcIjQ5NjAzNi44XCI6MzAwODYsXCI2MzMuNVwiOjYyMDEzLFwiOTAuNVwiOjc0MDc1LFwiODMuN1wiOjY4MDM5LFwiNjU2LjZcIjoxMDgxMzAsXCI5My44XCI6OTk5NTgsXCIxMDUuOFwiOjY4MDIxLFwiODIuNVwiOjEzNjA5NSxcIjYxMy4xOTk5OTk5OTk5OTk5XCI6MTM1MTYxLFwiODcuNlwiOjY4OTc3LFwiOTUuN1wiOjE0OTAyMixcIjcwMTI0Ljg4XCI6MTc5NjEsXCI1NDQ4NzAzMS43NjAwMDAwMDVcIjozMDAwMyxcIjEwMDE3Ljg0XCI6MTk5MTEsXCIxMDYuOFwiOjExNyxcIjU4MS42OTk5OTk5OTk5OTk5XCI6NTM2NjIsXCI4My4xXCI6MTQzNjQsXCI1Mi4zXCI6MTM4ODQ1LFwiNjMxLjRcIjo2ODAzMSxcIjg0LjdcIjo2Nzk5NyxcIjUyNi40XCI6NjE3MTUsXCI3NS4yXCI6NzMxOSxcIjk5LjlcIjo2OTQxNixcIjkyLjdcIjo2ODk5NSxcIjYwNC4xXCI6MjE4LFwiNDY5Mzg1LjdcIjoyMzMsXCI0Njg5MTYzMS40M1wiOjI5ODExLFwiNjAzNDkuNTkwMDAwMDAwMDA0XCI6MjkxNDgsXCI4NjIxLjM3XCI6ODY4NSxcIjY0MS4xOTk5OTk5OTk5OTk5XCI6NjgwMzAsXCI3MS45XCI6MjEyODI0LFwiNjMyLjFcIjoxMjA3MDIsXCI5Mi44XCI6NjgwNDEsXCI2OTYuNVwiOjUyODM3LFwiOTkuNVwiOjgzMjk0LFwiNTAzLjMwMDAwMDAwMDAwMDA3XCI6NTkzNTUsXCIxMTAuN1wiOjEzNjAyMSxcIjQ4Ny45MDAwMDAwMDAwMDAwM1wiOjExMTE0NCxcIjY5LjdcIjo5MzA1NSxcIjYwNC44MDAwMDAwMDAwMDAxXCI6NjExNTMsXCI4Ni40XCI6Njg3OCxcIjUyNy4xXCI6NjA1OTksXCI1NjA4My40NFwiOjE5NDI4LFwiNDM1NzY4MzIuODhcIjoyOTk2NyxcIjgwMTEuOTJcIjoxODU2MixcIjEwNi40XCI6MTE1MjQsXCI1NTguNlwiOjEyMzkzOCxcIjc5LjhcIjoxNDgxNTIsXCIzNjYuMDk5OTk5OTk5OTk5OTdcIjoxMzM4MTUsXCI2NjkuOVwiOjU1MDg1LFwiNzUuM1wiOjc1NTYwLFwiNzY3LjlcIjoxODAzOTAsXCIxMDkuN1wiOjkxNzE5LFwiNTkzLjZcIjoxNzY1OTgsXCI4NC44XCI6MTYzNTYyLFwiOTEuNlwiOjEzNjA4NixcIjc0NC44MDAwMDAwMDAwMDAxXCI6MTI0ODc0LFwiODMuMlwiOjY4MDc4LFwiOTAuM1wiOjE1MzI0LFwiNTc4NzA5LjYwMDAwMDAwMDFcIjoyMjMsXCIzMDI2NjUxMi4wODAwMDAwMDJcIjoyOTg0NSxcIjM4OTUzLjA0XCI6Mzc3NTZ9IiwibGFzdEhDQW1vdW50IjoyNzQzODQ3MjkyMjI0NjMzMjAwMCwibWF4SENQZXJjZW50Ijo2NTAxNjM5NjYwNjE1NzU1MDAwLCJsYXN0SENUaW1lIjoxNzA2NTc4MDk2ODk5LCJtYW5hTWF4Ijo5OSwibWF4U3BlY2lhbHMiOjEsIm9yYk1heCI6NDAwLCJwcmV2TGFzdEhDVGltZSI6MTcwNjU3ODA5Njc5OSwic2F2Ow%3D%3D%21END%21`

Do this in the console:

`Game.LoadMod("https://github.erbkaiser.com/FrozenCookies/frozen_cookies.js");`

Error message:

```
Uncaught SyntaxError: Unterminated string in JSON at position 3073 (line 1 column 3074)
    at JSON.parse (<anonymous>)
    at Object.setOverrides [as load] (fc_main.js?_=1706579890931:150:41)
    at Game.registerMod (main.js?v=10b:1063:46)
    at registerMod (fc_main.js?_=1706579890931:16:10)
    at loadScript (frozen_cookies.js:63:9)
    at Object.success (frozen_cookies.js:68:17)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at HTMLScriptElement.i (jquery-3.6.0.min.js:2:83436)
setOverrides @ fc_main.js?_=1706579890931:150
Game.registerMod @ main.js?v=10b:1063
registerMod @ fc_main.js?_=1706579890931:16
loadScript @ frozen_cookies.js:63

fc_main.js?_=1706579890931:4635 Uncaught TypeError: Cannot read properties of undefined (reading 'nextPurchase')
    at nextPurchase (fc_main.js?_=1706579890931:4635:33)
    at nextChainedPurchase (fc_main.js?_=1706579890931:4640:5)
    at delayAmount (fc_main.js?_=1706579890931:4494:21)
    at Array.updateTimers (fc_infobox.js?_=1706579890934:168:21)
    at Game.runModHook (main.js?v=10b:1112:26)
    at Game.Draw (main.js?v=10b:16760:8)
    at Game.Loop (main.js?v=10b:16814:26)
```

The most recent thing I did was savescum for and buy Wheat thins, but I'm not sure why that would be related.

EDIT: It looks like my save file got corrupted somehow, but only the mod data part of it?

EDIT: Yeah, if you base64 decode it, the end of the json got cut off somehow. Maybe if you copy and paste part of a cookie clicker save file, CC will happily load it and truncate mod data? This might actually be a CC bug not a FC bug lol. I'll just set my FC back up the way I want it, up to you what to do with this issue

**Comment by erbkaiser** [comment]
Yeah, this seems to be a save issue. The error seems to indicate nextPurchase is undefined... INSIDE the function that defines it. I'm going to close this since it is not something that will happen normally.
