### ISSUE TITLE
Potential time save for auto sweet

### ISSUE THREAD

**Issue by dsf3449** [erbkaiser/FrozenCookies#163]
Hi,

I was trying out auto sweet and I see that it's actually quite slow due to calling `Game.Ascend(1)` followed by hard-coded 10 second timeout before calling `Game.Reincarnate(1)`.

The related code can be found here https://github.com/erbkaiser/FrozenCookies/blob/5db387fc4cbf67535f361798769b63ef0373de20/fc_main.js#L2519-L2525

However, on my own I've been able to make this faster by simply directly calling `Game.Reincarnate(1)`, which skips the entire cookie breaking animation, skill tree, etc, and just puts you back into the main game with a clean slate. This method does appear to re-roll the Grimoire seed as well.

Is there any downside to skipping `Game.Ascend(1)` here? Maybe it was not allowed when this code was first written but appears to work now.

I can make it into a PR if there's no downside.

**Comment by erbkaiser** [comment]
Hi,

nice find.

There is no reason for the delay, I just copied the existing ascension code from later in the code. If you want to make a PR I'll merge it in, otherwise I can make the change myself in a few hours.

**Comment by dsf3449** [comment]
PR submitted
