### ISSUE TITLE
Butter Biscuits not being unlocked

### ISSUE THREAD

**Issue by HPsaucii** [erbkaiser/FrozenCookies#166]
I'm pretty sure that the auto-buy building feature of this mod breaks the butter biscuits, as none of them ever become unlocked to buy unless the user sells a bunch of buildings and rebuys them

**Comment by HPsaucii** [comment]
This issue seems to have fixed itself, ill keep this open incase it happens again

**Comment by erbkaiser** [comment]
The automatic dragon upgrade sacrifices buildings, this may explain it. And of course, Godzamok. There is also currently no logic to buy beyond any building limites to get all the biscuits (still planned, see #31)
Feel free to reopen if it happens again.
