### ISSUE TITLE
Auto Godzamok does not seem to work with just Pantheon unlocked

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#167]
I Just recently reset my progress and unlocked Pantheon with my first Sugar lump. I slotted in Godz, Dotj, and Muri, and when a click frenzy triggers, Auto Godzamok does not activate

**Comment by erbkaiser** [comment]
The script disables minigames that are not unlocked and requires a reload before it can work with any that are. Does it work after reloading?

See also #154
