### ISSUE TITLE
[Feature Request] Automating garden

### ISSUE THREAD

**Issue by TheOne320** [erbkaiser/FrozenCookies#168]
Like the title says I want a way to automate the garden for different setups and strategies.

**Comment by erbkaiser** [comment]
I've considered this before, but it's both very complex, AND there are already great mods that do it much better than I ever could.

Such as this one https://steamcommunity.com/sharedfiles/filedetails/?id=2855914280

**Comment by TheOne320** [comment]
Would that mod be fully compatible with your mod? So I can run both parallel?

**Comment by erbkaiser** [comment]
Yes, any garden mod will work with FC. You should avoid the 100% Consistency Combo for autocast if you are working on a garden, that is the only caveat.
Stock market mods should also work.
