### ISSUE TITLE
Problem with Auto Ascend

### ISSUE THREAD

**Issue by TheOne320** [erbkaiser/FrozenCookies#172]
![image](https://github.com/erbkaiser/FrozenCookies/assets/7705568/49c8afe6-8ebf-447d-a6b5-b8abd8ead4c5)
I have set auto ascend to ascend when prestige is doubled.
![image](https://github.com/erbkaiser/FrozenCookies/assets/7705568/7911bada-06d4-4d1a-9753-2595f6565c96)
As can be seen it would now be more than doubled.
No combo is active and nothing is happening. Does it only check at specific intervals or how does this work?

**Comment by erbkaiser** [comment]
It looks like it should have kicked in, based on your settings. No idea what may be causing it, perhaps it just gets stuck on the calculation somewhere. Try reloading the page/game, and if that also fails, manually ascend, and hope it kicks in next time.

**Comment by TheOne320** [comment]
I restarted multiple times and it never worked. I had to manually ascend. Is there some log file I can upload?
