### ISSUE TITLE
[Steam] FrozenCookies suddenly failed to load

### ISSUE THREAD

**Issue by mhetralla** [erbkaiser/FrozenCookies#173]
I'm subscribed to FrozenCookies through the Workshop, and I have using it for years now. Since yesterday, FrozenCookies is not loading. Console shows this error:  
`main.js?v=10:108 GET http://github.erbkaiser.com/FrozenCookies/frozen_cookies.js net::ERR_CONTENT_DECODING_FAILED 200 (OK`  
![image](https://github.com/erbkaiser/FrozenCookies/assets/15217237/fe9f88fa-13b6-49a0-ac03-00fe702e1c0e)  
![image](https://github.com/erbkaiser/FrozenCookies/assets/15217237/738fc515-051a-4552-a9b9-4e2e85777cdc)  
I have also tried to reinstall the game, and unsuscribe from all other mods, but I still get the error. I can force FrozenCookies to load if I do it with the command through the Console tab (like the Web version does). I have not enabled any firewall or new software that could be blocking the connection to GitHub.

**Comment by erbkaiser** [comment]
HTTP error 200 means the server request worked and it should get the rest of the content. As I host this entirely on GitHub, I have no insight on what might be blocking the actual script from being downloaded and executed at your end.
The script is still accessible.

**Comment by nrich239** [comment]
This is also happening in the web version
![image](https://github.com/erbkaiser/FrozenCookies/assets/168288715/25a6e82f-cc48-431b-8661-8112f7cf3dd0)
![image](https://github.com/erbkaiser/FrozenCookies/assets/168288715/b003400d-f46e-451d-b8b3-b86001aa9e7b)

**Comment by erbkaiser** [comment]
That is a DNS issue on your end. github.erbkaiser.com resolves to erbkaiser.github.io where the script is located.
