### ISSUE TITLE
fc not appearing in the top right

### ISSUE THREAD

**Issue by TheAidenPlace** [erbkaiser/FrozenCookies#174]
i tried downloading it via workshop and manually and neither times did frozen cookies show up. I disabled all other mods and still doesn't work. Please help

**Comment by erbkaiser** [comment]
That means it is not loading. Try installing again.

**Comment by TheAidenPlace** [comment]
i deleted it from local, added it back, still didnt work, then tried adding it to the workshop folder, and that still didnt work. I was using it on my browser for a few months too and it also suddenly stopped working

**Comment by erbkaiser** [comment]
Try to load the script from https://erbkaiser.github.io/FrozenCookies/frozen_cookies.js
Some net nanny programs appear to block github.erbkaiser.com

**Comment by TheAidenPlace** [comment]
clicking the link it gives me an error "DNS_PROBE_FINISHED_NXDOMAIN" and says this site cant be reached

**Comment by erbkaiser** [comment]
Then something on your end is blocking it. Try changing your DNS servers, or contact your internet provider.

**Comment by erbkaiser** [comment]
I assume this has been resolved.
