### ISSUE TITLE
FC should buy upgrades that don't provide CpS benefit

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#18]
Examples: Sacrificial Rolling Pin, "egg", idle upgrades.

These are never pushed to the buying list since they provide no CpS benefit that the mod can calculate. A system should be developed to purchase these anyway.

**Comment by erbkaiser** [comment]
Purchase code could be modelled on autoEaster

**Comment by erbkaiser** [comment]
Upgrade - id
Sacrificial rolling pins - 87
Weighted sleighs - 158
Santa's bottomless bag - 163
Dragon teddy bear - 651
Dragon fang - 650
Green yeast digestives - 473
Fern tea - 474
Ichor syrup - 475
Fortune 102 - 640
Omelette - 226
"egg" - 229

Sometimes these ARE bought:
Faberge egg - 223
Wrinklerspawn - 224

**Comment by Hringingy** [comment]
I think this should also include the various santa upgrades that lower purchase costs and affect reindeer spawns
