### ISSUE TITLE
Unable to view full Frenzy Times list

### ISSUE THREAD

**Issue by orlum** [erbkaiser/FrozenCookies#21]
The Frenzy Times section of the Frozen Cookies menu appears as a scrollable list, with only the first seven multipliers visible without scrolling down the list. There is a scroll bar to view the remaining list entries, however any attempt to scroll down fails. The list will begin scrolling but will then jump back to the top after about a quarter second. The issue occurs whether mousewheel scrolling, clicking in the area below the scrollbar, or clicking and dragging the scrollbar. I could not find any way to view the lower multipliers on the list without encountering the issue. This is on Steam version 2.048 with no other mods loaded. Issue persists after restart.

**Comment by erbkaiser** [comment]
Seems this broke a bit at some point. I think I'll fix it by moving the frenzy list down on the page, the reason I added the overflow was that in a long running game the list can get incredibly long so you need to scroll down forever to get to the options.
