### ISSUE TITLE
Building caps are sometimes ignored by autobuy

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#25]
Noticed this myself in testing.

If a Steam save with the Wizard Tower Cap (mana cap) set to a given value is imported in the web version, sometimes FC will rapidly begin buying Wizard towers up to the maximum possible, as if the value is not set.
Toggling the cap off and on, or reloading with the save present on reload seem to be the only fixes.

Settings: FrozenCookies.towerLimit & FrozenCookies.manaMax

This does not happen with the mineLimit and factoryLimit.

What is different about the towerLimit?

**Comment by erbkaiser** [comment]
To test: does this also happen if web is exported to Steam?

**Comment by erbkaiser** [comment]
Possible cause: Autobuy is enabled on load if it was previously enabled in FC settings, this sometimes runs before the buildingblacklist is completed.

Possible fix: turn off Autobuy whenever FC loads and only turn it on when load is complete.

**Comment by Icychocobo** [comment]
Toggling didn't fix it this time, and a refresh didn't either. It seems to be stopping at an arbitrary point sometimes.
After a refresh just now, it went and bought up to 200 towers. I turned autobuy off and on, and the same thing happened. It bought up to 200. But I noticed I had my _Sell_ value set to 100. Turning auto-buy off, setting myself to Buy, then the value to 1, it seemed to have started working again.
Wild guess, being not-at-all script savvy: If it just trying to buy too fast for it to detect or something?

**Comment by erbkaiser** [comment]
Pretty much yes. If you have bulkbuy set to 100, the autobuy system can glitch. I've got a fix in mind but it requires a lot of rewriting, so this has a low prio for me.

**Comment by Icychocobo** [comment]
Understandable, and I don't blame you. At the very least I now know a work-around, and others can see it. Thanks for the input, and thanks for the mod! I'll try to be a bit more vigorous when looking through the issues next time. I somehow overlooked this one.

**Comment by erbkaiser** [comment]
No problem, and please keep reporting any issues you may find.

**Comment by erbkaiser** [comment]
Also appears to happen without bulk buy modifiers sometimes.

**Comment by erbkaiser** [comment]
Possibly fixed by commit 02ac3527bd225c72c3d3e681cbde92098fc69c24 - disable autobuy during click frenzies

As a CF tends to be at the root of all big combos, temporarily not allowing autobuy during it (auto-Godz has its own mechanics) might be a fix.

**Comment by erbkaiser** [comment]
@[Icychocobo](https://github.com/Icychocobo)  @[Gr3atsaga](https://github.com/Gr3atsaga) if you have the chance, please let me know if you still see Autobuy ignore building caps with the current build and if it does, what your bulk buy option is (if any).

The expected behaviour with FC autobuy enabled is now that it will not autobuy during a click buff (except for Godzamok buildings and/or Wizard towers), but it should kick back in immediately after the click buff ends.

**Comment by Icychocobo** [comment]
It hasn't been misbehaving for me the last few days, but I've had my Bulk Buy set to 1 for everything but the first few minutes of a run. On my next ascension (might be a bit. Waiting on the FtHoF dualcast combo) I'll set it to 100 and leave it there for the whole time, see if it wants to act up.
I'll note that I do have Godzamok in my diamond slot, but I've only ever had issues with my Wizard Towers. I can probably see if it wants to misbehave in the regard.

I will also note that in the last few ascensions, the silly thing buys me up to 102 mana during the bulk buy period, but that was before the most recent build. Again, I'll keep you updated here when the next ascension rolls around.

**Comment by Icychocobo** [comment]
Update: 
New ascension left at 100 bulk buy has, thus far, shown no issues. The game once again went up to 102 mana worth of towers (549 towers at level 1), but then stopped. The script is also respecting my cap on Factories and Mines, set at 650. Thus far, I've had no issues during roughly 6 hours of running time between this ascension and my last one.
The overshoot seems reasonable on the wizard towers. I saw it somehow managed to get 99 towers early on, then it continued buying them is sets of 50 or 100, which led to 549 before it stopped and respected the cap.

Overall, I'd say it's working.

Quick Edit: Decided to monkey with it a bit. I sold down to 539 towers with autobuy off. Flipping it to 100 bulk buy and turning it back on, it overshot up to 689 towers. So it's not _ignoring_ it now, just overshooting sometimes.

**Comment by erbkaiser** [comment]
This should now be fixed.
