### ISSUE TITLE
Automatically set dragon auras

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#29]
Add an option for the primary and secondary dragon aura and set these automatically once possible.

Needs to also destroy the most expensive building without selling, to do this in a non-cheating way.

**Comment by erbkaiser** [comment]
1st slot = ,0 and 2nd slot = ,1
Game.SetDragonAura(1, 0); - simulates clicking on the aura selector
Game.ConfirmPrompt(); - confirms without user interaction

Write code to have this run as soon as a slot can be selected and the user chosen aura for that slot is available.
Add a preference option with all auras listed per slot, use the same numbers to make setting it easier.
Possibly add fallback if user is dumb and sets a later unlocked aura for slot 1?

**Comment by Hringingy** [comment]
Can you add something like a dedicated switch to enable/disable setting auras? I'm using different setups between farming seasonal drops in the beginning of a run (Dragon Orbs/Mind over Matter) and a production focused setup once I've obtained the necessary drops (Elder Battalion/Dragonflight). I'd like to be able to automatically slot the early game setup and manually switch things later, but the current implementation is a bit cumbersome to turn on/off.
