### ISSUE TITLE
Mana Cap potenitally broken?

### ISSUE THREAD

**Issue by Icychocobo** [erbkaiser/FrozenCookies#40]
Pretty much the title. 
I've been futzing with the Mana Cap toggle for a bit, changing other auto-buy settings, the mana cap, turning the cap on and off again. No luck. It seems like the Mana Cap is no longer being taken into consideration for purchasing Wizard Towers.
It makes some sense, since the automatic Sugar Frenzy mana generation thingamabob was just added. It may have broken something. I'd go in and try fixing it myself, but I have all the scripting knowledge of a one-legged newt.

**Comment by erbkaiser** [comment]
It's most likely a race condition, sometimes for whatever reason the game ignores this cap. Saving and reloading or toggling the option should fix it.

See #25
