### ISSUE TITLE
Manually selling mines and factories to trigger Godzamok doesn't respect building limits with auto buy

### ISSUE THREAD

**Issue by Gr3atsaga** [erbkaiser/FrozenCookies#42]
Occasionally I will manually trigger Godzamok if there is decent buffs happening. I have the mine limit set to 820 and the factory limit set to 800. This seems to do well once I've gotten into the octodecillions,  Just enough that buying the last few costs just a few septendecillions.

However, as soon as I sell the buildings manually to trigger the buff, the mod auto buys them and doesn't stop until it deems factories and mines are no longer the most efficient option which may be 40-80 buildings over the set limits. Therefore spending everything that the buff generates.

**Comment by erbkaiser** [comment]
Do you have one of the bulk buy modifiers 10/100 active? Autobuy doesn't seem to work well with these.

**Comment by Gr3atsaga** [comment]
I do not.

**Comment by erbkaiser** [comment]
Possibly related to #25 

Autobuy doesn't seem to check limits at times.

**Comment by erbkaiser** [comment]
Merging into #25 as I'm sure it's a general issue with autobuy
