### ISSUE TITLE
Frozen Cookies Is too Powerful

### ISSUE THREAD

**Issue by Jaxlyfe** [erbkaiser/FrozenCookies#54]
This issue is more of a performance one. I have tried all the suggested steps to try fixing this issue.

Its simply that frozen cookies after ascension or during a buying fest the game slows right down, yet is not using more of my computers resources. I'm not sure if this is a game limitation or not.

**Comment by Jaxlyfe** [comment]
Also, would you be able to add a buy all upgrades switch for easier 1000 ascension pace

**Comment by erbkaiser** [comment]
Can't do much about the game slowing down. That's a limitation of the Javascript code interpreter in the browser (even on Steam).

Turning off purchase logging and other stats may help.

I've opened a feature request for the buy all thing. Should be doable.
