### ISSUE TITLE
Have autobuy ignore vaulted upgrades

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#56]
I was wanting to experiment with using the "Cosmic Beginner's Luck" upgrade to try and rush through the seasonal upgrades. The problem is that auto buy will purchase Heavenly Chip Secret even when I vault the upgrade. I'd like to request a change to the autobuy feature so that it specifically ignores upgrades placed into the vault

**Comment by erbkaiser** [comment]
Thanks for requesting this. It's been on my todo list for a while, so I definitely will try to get it working.

**Comment by erbkaiser** [comment]
Useful code
				var me=Game.UpgradesInStore[i];
				if (!me.isVaulted() && me.pool!='toggle' && me.pool!='tech') me.buy(1);

**Comment by erbkaiser** [comment]
Implemented.
Since the Heavenly Chip Secret is bought almost immediately, you should turn off AutoBuy before ascending, in order to get the chance to vault it. Once AB is turned on again it will ignore any vaulted upgrades.
