### ISSUE TITLE
Infobox GC timers and autocasting not working properly 

### ISSUE THREAD

**Issue by valkyriaivan** [erbkaiser/FrozenCookies#58]
I'm currently playing in the version 2.048 with the latest update of the mod and the infobox and autocasting aren't working properly. 

I was thinking about making 2 different issues, but since both of this appear in the same version and config, maybe it's easier to scope.

I have other mods installed but made sure to remove any that used CCSE since it's giving problems still. And I have no other mod issues cause by CCSE, like the changing seasons, which I had before disabling other mods:
![image](https://i.gyazo.com/35d7c7ec66e3703398b0d19066057416.png)
First the infobox. I'm using the text only infobox and the timers for the next purchase and active buff are working properly. But the GC timers show a count and when it reaches 0, no GC has appeared and the textbox stops showing the timers for the GC.
![alt text](https://i.gyazo.com/57181a5ff87d7071b29de966603af795.png)

The issue with autocasting is that when the mana is full, and it's set to autocast FTHOF with a minimum of x7 Frenzy, it doesn't activate even with an active frenzy + building buff. When the next cast is a clot or useless cookie, it casts another spell to cicle.
The problem is that it never cast frenzy or click buff, maybe some other options that I haven't seen. This are my settings: 
![alt text](https://i.gyazo.com/b32b190f4e45280e7bfe843bf9b86690.png)

**Comment by erbkaiser** [comment]
Can you give more info? What is it doing now, what is the expected behaviour, at which stage are you etc.?

**Comment by valkyriaivan** [comment]
> Can you give more info? What is it doing now, what is the expected behaviour, at which stage are you etc.?

Sorry, updated the post, accidentaly posted before writing it. If you need any screenshots or info tell me

**Comment by erbkaiser** [comment]
The GC timer disappearing is something I've seen myself, not sure yet what might be causing it. There appear to be some game conditions that just stop cookie spawning but it's not that the Golden Switch is active then.
It should automatically reset after some time.

As for autocasting, if the next spell is a clot or ruin cookies AND you are suffering from a clot or loan interest that sets your effective frenzy below 1, it will cast Stretch Time instead to shorten the debuff.
If you do not have a current clot, it will cast Haggler's charm instead of FTHOF if the next spell is Ruin cookies, Clot, Blab, or a Cookie Storm (Drop).

**Comment by valkyriaivan** [comment]
The GC timer used to be around 1m 30/50 seconds, and now it is max 1 minute, I don't know why, maybe it0s calculating something wrong now. It isn't really a problem, just wanted to give a heads up.

The thing with the autocasting is that without having a clot or interest, doesn't matter if the mana is full and there is a click frenzy next. In this screenshot I had x7 minimum frenzy and a frenzy active, no debuffs and the next speel is a click frenzy. I tried setting it to x1 and x0 and it doesn't cast anything. The other behavior you said seems to work fine.
![alt text](https://i.gyazo.com/ab4336de4cbe524007053ba1e917b353.jpg)

**Comment by erbkaiser** [comment]
You're absolutely right about auto cast not working right. I fixed it now (by rewriting most of it).
It's now also documented in the readme.

I'll close this issue with the PR.

As for the timers, it's not related to the auto casting so should get its own issue, which I'll open myself once I get some more idea of WHY it breaks sometimes.
