### ISSUE TITLE
Loading Frozen Cookies caps Cortex Bakers at 399

### ISSUE THREAD

**Issue by gentrygeissler** [erbkaiser/FrozenCookies#62]
If I load the latest version of the bookmarklet, my cortex bakers are reverted to 399. If I try to buy more, the value is set back to 399 within about a second. 

I recreated this on a Private tab of Firefox with no changes made to the Frozen Cookie settings. I have a video recording of this happening, but I can't seem to get it uploaded to github. Contact me privately and I can provide a google drive or dropbox link.

**Comment by Jofroi** [comment]
I am having the same problem since yesterday with the steam app.

The bug disappear when I remove the Auto  cast "FTHOF" so I believe it is related to the release of the 12th of July.

**Comment by erbkaiser** [comment]
Should be fixed now. Can you test and confirm?

**Comment by Jofroi** [comment]
It seems fixed on steam indeed. Thanks for the fast fix.
