### ISSUE TITLE
Add a dedicated toggle for Dragon Auras

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#65]
Can you add something like a dedicated switch to enable/disable setting auras? I'm using different setups between farming seasonal drops in the beginning of a run (Dragon Orbs/Mind over Matter) and a production focused setup once I've obtained the necessary drops (Elder Battalion/Dragonflight). I'd like to be able to automatically slot the early game setup and manually switch things later, but the current implementation is a bit cumbersome to turn on/off.

_Originally posted by @Hringingy in https://github.com/erbkaiser/FrozenCookies/issues/29#issuecomment-1188285989_

**Comment by erbkaiser** [comment]
That was easier to do than I expected and is live now.
I'll take a look at your other ideas later this week.

**Comment by Hringingy** [comment]
thank you!
