### ISSUE TITLE
add automation/blacklist option for Dragon Orbs wishing

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#66]
While doing some more experimenting with starting a run, I found a strategy of using the Dragon Orbs' wish mechanic during Easter to both kickstart early game production and potentially trigger a cookie storm sooner for the drops. I was wondering if it would be possible to automate this wish mechanic when Dragon Orbs (and/or Reality Bending) is slotted on Krumblor, possibly even with an option to also wait until Easter.

My starting setup:
I've set my Pantheon to not auto slot Godzamok, and I keep loans/autocasting disabled until I've finished farming easter drops.
Dragon is set to Dragon Orbs/Mind Over Matter.

**Comment by erbkaiser** [comment]
I did some investigation in this but I won't implement this. Scripting will be very complex for limited results, since at best, you get an 11% chance of a cookie for selling the biggest building and it requires the last dragon aura, so the timeframe in which this would seem useful is very limited.
The existing switches should allow you to set it up yourself.

**Comment by Hringingy** [comment]
Not even a simple blacklist for cortex bakers or a switch to sell cortex bakers one at a time when no buffs are active?

**Comment by erbkaiser** [comment]
Gonna try if I can get this to work after all.
Do you know if Dragon Orbs can work if a non-CpS or click bonus (Haggler's Charm, specifically) is active?

**Comment by Hringingy** [comment]
It looks like any and all effects will stop Dragon Orbs. Spells, Godzamok, and even Loan Interest stops the wish mechanic.

**Comment by Hringingy** [comment]
I would be fine with still having to manually turn all of those off,

**Comment by erbkaiser** [comment]
So hey this is working now. Have fun with it 👍

**Comment by Hringingy** [comment]
Thank you!

**Comment by Hringingy** [comment]
Bug: Cortex Baker limit seems to be misapplying to JavaScript Consoles instead

**Comment by erbkaiser** [comment]
That means Cortex Bakers weren't being blocked properly for Spontaneous Edicife either... weird how noone noticed it before.

Fixed.

**Comment by Hringingy** [comment]
Bug: Autosell of Cortex Bakers stop when a cookie chain is triggered from Dragon Orb wish. I've noticed that wishing needs to repeatedly trigger in order to finish a Cookie Chain that is started from wishing

**Comment by erbkaiser** [comment]
That's intentional. There is no way (that I know of) to check if the game is in the middle of a cookie chain so I have it stop selling CBs once a cookie chain starts. Without this check, it will continually keep spamming CBs even while the chain is active.

**Comment by Hringingy** [comment]
What I'm saying is CBs NEED to keep being sold in order to continue the chain as Cookie Chains started by wishing don't act like naturally generated ones. the next Golden Cookie in the wished chain doesn't spawn via timer, but by triggering more wishes.

**Comment by erbkaiser** [comment]
I trust you know better than I do here, so I removed that check.

**Comment by Hringingy** [comment]
This weird behavior with wished in Cookie Chains is probably a bug with Cookie Clicker itself

**Comment by Hringingy** [comment]
Minor Bug: auto selling Cortex bakers sometimes causes auto Brokers to trigger when it otherwise wouldn't, possibly due to rebuying the Building.

**Comment by Hringingy** [comment]
I can't seem to get Auto Dragon Orbs to work anymore. Do you know what might be causing this?
