### ISSUE TITLE
Can't get 100% Consistency combo to work

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#70]
When I tried toggling the 100% Consistency Combo, it doesn't seem to do anything, even with all the prereqs met on the Readme. Am I doing something wrong? I can give a copy of my save if needed

**Comment by erbkaiser** [comment]
These are the full prereqs:

-Wizard tower level 10
-98 or more max mana
-1 free sugar lump (101 if using sugar baking guard)
-fully upgraded dragon so you can run Dragon's Fortune adnd Radiant Appetite (will swap in if needed)
-Mokalsium and Godzamok slotted, or enough free swaps
-Whiskerbloom unlocked in the garden

It will then wait until it has a click frenzy and building special or elder frenzy, and fire when you have a frenzy or dragon harvest and a building special.

If you match all those, I suspect the whiskerbloom check may be failing... the garden is tricky. Let me know if you match everything and I'll push a branch with the wk check disabled, to test.

**Comment by Hringingy** [comment]
Mi4wNDh8fDE2NTg2NjY4OTQ3ODU7MTY1NzIyMDIxNTU3NzsxNjU4NzE5NDcxMTExO0hyaW5naW5neTt5a3FieHwwMTExMTAwMDExMDAxMDExMDExMTAxMDAwMTF8MS41MTc2NDc3ODM3MTYyODg0ZSs2MjsxLjI5NDM2NzcwMDIxMjM4MjVlKzY1OzE2MTQ3MjM7MTE3NjA7MS4yODU4Njk4MzY5MDMyNDZlKzY1Ozc7MjM7MTY7Mi4xODUzMzU1Mjk3MjE1MzU0ZSs2OTswOzE4OzM5NDgzOzA7LTE7MjI2Ozg2MzsyLjM0Njc3ODA4ODgwNjg2ODRlKzU2OzgyOzE0OzM5OzEzNTg0MDg7NTtoYWxsb3dlZW47MDswOzEyOTc2ODcwMzQ4NjkyMDc3MDAwOzEyOTI3NzQ1MTc1MjE0ODk3MDAwOzQ5MTIwNzg5OTI0NDYzNTIwOzA7MDs3NjY7NzYwOzY0MTsxNTI7MjI2OzI2OzQ7OTswOzA7MDswOzEyMTsxMzM0OzE2NTg2NzI4NDY5MDA7MDsxOzIyNzsxMDA7MTsxOzIuMjIwMzI5NjYzMTg2MTc4ZSs1NTs3NTt8MTAyNiwzMjI2LDUuOTY0MDY5MzYwMDgyOTU4ZSs2MCwyMCwsMCwxMDI2OzEwMTUsMTM2NSwxLjE4NDIxNzQ4NzI3MzQwOWUrNjAsMTAsLDEsMTAxNTs5ODksMTMzOSwyLjU4MTY2NjU4NTI3NjIyOGUrNjAsMTAsMTY1ODcxOTYyMzc0ODoxOjE2NTg3MTkzMjM2MzU6MDoyODM6MTkxMjY6MToxOjE2NTg2NjY4OTQ3OTI6IDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEgMTc6MDoxNzowOjE3OjA6MTc6MDoxNzowOjE3OjA6NjowOjY6MDo2OjA6NjowOjY6MDo2OjA6MTc6MDoxNzowOjE3OjA6MTc6MDoxNzowOjE3OjA6NjowOjY6MDo2OjA6NjowOjY6MDo2OjA6MTc6MDoxNzowOjE3OjA6MTc6MDoxNzowOjE3OjA6NjowOjY6MDo2OjA6NjowOjY6MDo2OjA6LDAsOTg5OzkyNSw0MDI3NSw2LjUxNDgwNjU1NDMzMDY4NWUrNjAsMTAsLDEsOTI1OzkwMCw0MDI1MCw2LjQzNzA5MDQyNDMyNTk5OWUrNTksMTAsLDEsOTAwOzkyMiwxMjczLDcuODQ3NTY5MTU4OTgxODI4ZSs1OCwxMCw1OjExMjowOjEzNzU5Ni40Mzg4NzI4MzgxNjoxOiA5Njk6NTotNDI6NjUzOjE4MzQ6MDowOjY1NiE0MTI1OjU6LTg1OjY4OjE3Mzg6MDowOjc0MyEzMDkwOjU6Mzc6NjExOjE3MDA6MDowOjM3OTYhNDg3MToyOjUxOjMxODowOjA6MDo0MDAxITI4OTM6MTotNTY6MTk6MTczMDowOjA6NjU3ITkyOToyOi04MjozNTU6MTU5MjowOjA6MzAzOCExMjQ5OjM6ODoyNDA6MTY2MTowOjA6MjU4ITE4NDM6NToxNDoyNjg6MTYyNTowOjA6NzAyOCE2NTQ2OjE6LTY0OjQzNjoxNjA5OjA6MDo1ODQ5ITQ3NzM6MjotMTM2OjYyOjE1Njc6MDowOjIyMDchMjY5OTo1OjU1OjQ1MzoxNTUwOjA6MDoxMjM3ITk3NzE6MTo4MDo1OTM6MTUzMTowOjA6NTU1OSE5NzEwOjE6LTQwOjk1OjE0OTg6MDowOjg0NDMhNjE2NzoyOi00ODozNDk6MTQ4MzowOjA6NTc3NiE2OTYzOjE6MjM6MjExOjE0MDk6MDowOjEyNzEyITEzNTk1OjE6Mzc6NDk2OjEzNjk6MDowOjEwNzIwITE1Mzg3OjU6LTI1Ojc4OjEzMjU6MDowOjEzMTQ3ISAxLDAsOTIyOzkyMSwxMjcxLDcuOTc5NjM5MzgyMjYzMzE3ZSs2MCwxMCwyLzQvNiAzIDE2NTg2Njk4Nzk5OTIgMSwwLDkyMTs0ODcsMTE5MCwyLjI5NDI1NzA5MDg1MzUzMDJlKzU4LDEwLDEwMCAyIDE0MTAgMSwwLDgyODs4NzQsMTIyNCw1LjYzMjkwNzQ0MjcxNjYyMjZlKzU3LDEwLCwxLDg3NDs4NTAsMTIwMCwxLjU5NDMyODIxMTU3MTcwNzdlKzU4LDEwLCwxLDg1MDs4NDAsMTE5MCwyLjUwMzk0MDgzNzc3MDg5OTJlKzYwLDEwLCwxLDg0MDs4MTIsMTE2MiwyLjYxNDM1MTUxNDMzNDczN2UrNTksMTAsLDEsODEyOzgwMCwxMTUwLDEuNzYzNTk5ODQ1ODY4ODUwM2UrNjAsMTAsLDEsODAwOzc4NywxMTM3LDUuMDY3NjMyMTcwODI1OTMyZSs2MCwxMCwsMSw3ODc7NzY2LDExMTYsNi43NDYwODE4NDczNjQ5MThlKzYwLDEwLCwxLDc2Njs3NTUsMTEwNSwyLjY1Nzg0MjQwMTY4NDc4NGUrNjEsMTAsLDEsNzU1OzcwNywxMDU3LDIuODU5MTgzODk1MTc3NDg4NmUrNjAsMTAsLDEsNzA3OzY3OSwxMDI5LDEuMDA5MzUwODA3NTgxNjY5MWUrNjEsMTAsLDEsNjc5OzY1MCwxMjg3LDQuNjU5ODQ5OTYwNTIwNTI4ZSs2MSwxMCwsMSw2NTA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTEwMDEwMDAxMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTAxMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTEwMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExfDI0LDUxODQwMDAsMzgwNTI5MywxLjI7MCw0MDQ2MzEsMzk4ODMyLDc7fGNvb2tpZWdhcmRlbmhlbHBlcnJlbG9hZGVkOnsidGltZXJJbnRlcnZhbCI6MTAwMCwiYXV0b0hhcnZlc3QiOnRydWUsImF1dG9IYXJ2ZXN0TmV3U2VlZHMiOnRydWUsImF1dG9IYXJ2ZXN0TWF0dXJlZCI6ZmFsc2UsImF1dG9IYXJ2ZXN0QXZvaWRJbW1vcnRhbHMiOnRydWUsImF1dG9IYXJ2ZXN0V2VlZHMiOnRydWUsImF1dG9IYXJ2ZXN0Q2xlYW5HYXJkZW4iOmZhbHNlLCJhdXRvSGFydmVzdENoZWNrQ3BTTXVsdCI6ZmFsc2UsImF1dG9IYXJ2ZXN0TWluaUNwU011bHQiOnsidmFsdWUiOjEsIm1pbiI6MH0sImF1dG9IYXJ2ZXN0RHlpbmciOnRydWUsImF1dG9IYXJ2ZXN0RHlpbmdTZWNvbmRzIjo1LCJhdXRvSGFydmVzdENoZWNrQ3BTTXVsdER5aW5nIjpmYWxzZSwiYXV0b0hhcnZlc3RNaW5pQ3BTTXVsdER5aW5nIjp7InZhbHVlIjoxLCJtaW4iOjB9LCJhdXRvUGxhbnQiOnRydWUsImF1dG9QbGFudEF2b2lkQnVmZnMiOmZhbHNlLCJhdXRvUGxhbnRSb3RhdGVTb2lsIjp0cnVlLCJhdXRvUGxhbnRSb3RhdGVTb2lsQ29tYm8iOjAsImF1dG9QbGFudENoZWNrQ3BTTXVsdCI6dHJ1ZSwiYXV0b1BsYW50TWF4aUNwU011bHQiOnsidmFsdWUiOiIxMyIsIm1pbiI6MH0sImF1dG9Gb3JjZVRpY2tzIjpmYWxzZSwic2F2ZWRQbG90IjpbW1sxNywwXSxbMTcsMF0sWzE3LDBdLFsxNywwXSxbMTcsMF0sWzE3LDBdXSxbWzYsMF0sWzYsMF0sWzYsMF0sWzYsMF0sWzYsMF0sWzYsMF1dLFtbMTcsMF0sWzE3LDBdLFsxNywwXSxbMTcsMF0sWzE3LDBdLFsxNywwXV0sW1s2LDBdLFs2LDBdLFs2LDBdLFs2LDBdLFs2LDBdLFs2LDBdXSxbWzE3LDBdLFsxNywwXSxbMTcsMF0sWzE3LDBdLFsxNywwXSxbMTcsMF1dLFtbNiwwXSxbNiwwXSxbNiwwXSxbNiwwXSxbNiwwXSxbNiwwXV1dLCJwcm90ZWN0ZWRTZWVkcyI6W10sImF1dG9QbGFudFJvdGF0ZVNvaWxDb21ib05hbWUiOmZhbHNlfTtmcm96ZW5fY29va2llczp7ImNsaWNraW5nT3B0aW9ucyI6MCwiYXV0b0NsaWNrIjoxLCJhdXRvRnJlbnp5IjowLCJhdXRvR0MiOjEsImF1dG9SZWluZGVlciI6MSwiYXV0b0ZvcnR1bmUiOjEsImJ1eWluZ09wdGlvbnMiOjAsImF1dG9CdXkiOjEsIm90aGVyVXBncmFkZXMiOjEsImF1dG9CdWxrIjoyLCJhdXRvQmxhY2tsaXN0T2ZmIjoxLCJibGFja2xpc3QiOjAsIm1pbmVMaW1pdCI6MSwiZmFjdG9yeUxpbWl0IjoxLCJwYXN0ZW1vZGUiOjAsImF1dG9PdGhlck9wdGlvbnMiOjAsImF1dG9Bc2NlbmQiOjAsImF1dG9Xcmlua2xlciI6MSwic2hpbnlQb3AiOjAsImF1dG9TTCI6MSwic3VnYXJCYWtpbmdHdWFyZCI6MSwiYXV0b0dTIjoxLCJhdXRvR29kemFtb2siOjEsImF1dG9Ccm9rZXIiOjEsImF1dG9Mb2FuIjoxLCJ3b3JzaGlwT3B0aW9ucyI6MCwiYXV0b1dvcnNoaXBUb2dnbGUiOjAsImF1dG9Xb3JzaGlwMCI6MCwiYXV0b1dvcnNoaXAxIjo0LCJhdXRvV29yc2hpcDIiOjAsInNwZWxsT3B0aW9ucyI6MCwidG93ZXJMaW1pdCI6MSwiYXV0b1NwZWxsIjowLCJhdXRvU3VnYXJGcmVuenkiOjEsInNwZWxsTm90ZXMiOjAsImF1dG9GVEhPRkNvbWJvIjowLCJhdXRvMTAwQ29uc2lzdGVuY3lDb21ibyI6MSwiYXV0b1N3ZWV0IjowLCJkcmFnb25PcHRpb25zIjowLCJhdXRvRHJhZ29uIjoxLCJwZXREcmFnb24iOjEsImF1dG9EcmFnb25Ub2dnbGUiOjAsImRyYWdvbk5vdGVzIjowLCJhdXRvRHJhZ29uQXVyYTEiOjE5LCJhdXRvRHJhZ29uQXVyYTIiOjEwLCJhdXRvRHJhZ29uT3JicyI6MCwiY29ydGV4TGltaXQiOjEsInNlYXNvbk9wdGlvbnMiOjAsImRlZmF1bHRTZWFzb24iOjQsImF1dG9FYXN0ZXIiOjAsImF1dG9IYWxsb3dlZW4iOjAsImJhbmtPcHRpb25zIjowLCJob2xkU0VCYW5rIjowLCJzZXRIYXJ2ZXN0QmFua1BsYW50IjowLCJzZXRIYXJ2ZXN0QmFua1R5cGUiOjAsIm90aGVyT3B0aW9ucyI6MCwiRkNzaG9ydGN1dHMiOjEsInNpbXVsYXRlZEdDUGVyY2VudCI6MSwiZGlzcGxheU9wdGlvbnMiOjAsInNob3dNaXNzZWRDb29raWVzIjowLCJudW1iZXJEaXNwbGF5IjoxLCJmYW5jeXVpIjozLCJsb2dnaW5nIjowLCJwdXJjaGFzZUxvZyI6MCwic2xvd09wdGlvbnMiOjAsImZwc01vZGlmaWVyIjoyLCJ0cmFja1N0YXRzIjowLCJmcmVuenlDbGlja1NwZWVkIjoyNTAsImNvb2tpZUNsaWNrU3BlZWQiOjEyNSwiSENBc2NlbmRBbW91bnQiOjEsIm1pbmVNYXgiOjkyNSwiZmFjdG9yeU1heCI6OTAwLCJtaW5DcFNNdWx0IjoxLCJtaW5Mb2FuTXVsdCI6MTAwMCwiZnJlbnp5VGltZXMiOiJ7XCIxXCI6Mzc3NTMwLFwiN1wiOjExNjg0OTMsXCI1NjdcIjoyNjIyMyxcIjY1MVwiOjY5MDM3LFwiNzc3XCI6MTA5NzY3LFwiMTExMVwiOjIzMDE5LFwiNDY2MlwiOjI4MTA2LFwiOTYzOVwiOjQyODYwLFwiNjEuOVwiOjM0MDA0LFwiOTEuN1wiOjY5MDQ4LFwiNTEzLjgwMDAwMDAwMDAwMDFcIjoyMDUzOSxcIjczLjRcIjo0ODUxMyxcIjMuNVwiOjE5NzE0NSxcIjAuNVwiOjQxMTAxOCxcIjEuMlwiOjU0ODQ5NSxcIjAuNlwiOjMwNDA2MixcIjguNFwiOjMzNTMxOTc5LFwiMTQyLjhcIjo4NTc4MDg1LFwiNzI1Ljc2MDAwMDAwMDAwMDFcIjo2OTA4OSxcIjY1MjYuOFwiOjcxMjgyOCxcIjIwLjRcIjo0MDk4NzAsXCIxNDIuNzk5OTk5OTk5OTk5OThcIjozMTc4MyxcIjY3OC43MlwiOjY5MDgyLFwiNzQ2Ljc2MDAwMDAwMDAwMDFcIjo2OTA2NCxcIjY1Ni4wNFwiOjY5MTQwLFwiNzgzLjcyXCI6NjkwNjAsXCI2ODQuNlwiOjM1MzMxNyxcIjcxNy4zNjAwMDAwMDAwMDAxXCI6NjkwNzcsXCI2NDMuNDM5OTk5OTk5OTk5OVwiOjkzODEsXCI5MS45MTk5OTk5OTk5OTk5OVwiOjU5NjY3LFwiOTc5Ni4wOFwiOjY5MTAxLFwiMTA5NTIuNzYwMDAwMDAwMDAyXCI6MTkyMjgsXCIxNTY0LjY3OTk5OTk5OTk5OThcIjo0OTc4NixcIjc4NS40XCI6MTg5MDQ2LFwiODM1LjgwMDAwMDAwMDAwMDFcIjo1NjU3NixcIjY0OTQxNi42MDAwMDAwMDAxXCI6MTI0MzYsXCI2NzYuMlwiOjY5MDUxLFwiNzY2LjkyXCI6NjkwNDMsXCIxMDgyNC4yNFwiOjY2MDE4LFwiNjM2LjcyXCI6MzA5MSxcIjExMDk1NS42XCI6MjEzNjYwLFwiNzMxLjY0XCI6NjkwODIsXCI1NTQuNFwiOjY5MDEyLFwiOTQyNC44MDAwMDAwMDAwMDFcIjo2OTAwMSxcIjU2MS4xMlwiOjEzODEwNSxcIjc2NC40XCI6MjM2MjQ4LFwiNjczLjY4MDAwMDAwMDAwMDFcIjo2OTU5OSxcIjExNjM4LjJcIjozODk3NyxcIjg2My41MlwiOjIwODAwMixcIjc3Ni4xNjAwMDAwMDAwMDAxXCI6MTE3OTU4LFwiNjQ1LjEyXCI6MjMzMDA5LFwiMTI1MjMuNTYwMDAwMDAwMDAxXCI6NjA1NDQsXCI3MzYuNjgwMDAwMDAwMDAwMVwiOjc3NTA2LFwiODMzLjI4MDAwMDAwMDAwMDFcIjo2OTAzMSxcIjEzMjA5LjAwMDAwMDAwMDAwMlwiOjU4MzI2LFwiNjQ1Ljk2XCI6MTU5MDEwLFwiNTczLjcyXCI6MTQ2MDAzLFwiNjY0LjQzOTk5OTk5OTk5OTlcIjoxNzE5NTUsXCI2NzQuNTJcIjo2OTAxNCxcIjg1NS45NlwiOjY5MDg2LFwiODY2LjA0XCI6NjkwMTQsXCI0MTcuNDhcIjoyODczMDYsXCI1OTguMDhcIjo2OTAxNyxcIjY0MC4wOFwiOjY5MDcyLFwiNjQ5LjMyXCI6MTM4MDk4LFwiODY3LjcyXCI6NjkwNzQsXCI3MTEuNDhcIjoxMzgwNzEsXCI1OTM5MzguNzk5OTk5OTk5OVwiOjg5NSxcIjg1OS4zMlwiOjY5MDQ5LFwiODM3LjQ4XCI6NjkwMzgsXCI3MDk3LjE2MDAwMDAwMDAwMVwiOjM0MDQ2LFwiNzA5Ny4xNlwiOjI0MDc4LFwiODcwLjI0XCI6NjkwNjQsXCI2NjkuNDhcIjo2OTEwMSxcIjgzOS4xNjAwMDAwMDAwMDAxXCI6MTM4MTMzLFwiMTMzNTEuOFwiOjE4MTQ2LFwiNjg5LjY0XCI6NjkwOTYsXCI3ODEuMlwiOjY5MDg4fSIsImxhc3RIQ0Ftb3VudCI6MTI5NzcyMDg1MjAxNTczNDQwMDAsIm1heEhDUGVyY2VudCI6NDU3MjU2NDMzMjI4ODIyMzAwMCwibGFzdEhDVGltZSI6MTY1ODcxOTQ3MTA2NSwibWFuYU1heCI6MTAwLCJtYXhTcGVjaWFscyI6MSwiY29ydGV4TWF4Ijo1MDAsInByZXZMYXN0SENUaW1lIjoxNjU4NzE5NDcwOTYyLCJzYXZlVmVyc2lvbiI6IjIuMC4wIn07TUVUQToqQ0NTRSwqY29vbGVyIHNhbXBsZSBtb2QsKmxhbmcgc2FtcGxlIG1vZCwqc2FtcGxlIG1vZCxmcm96ZW5fY29va2llcywqY29va2llYXNzaXN0YW50LGNvb2tpZWdhcmRlbmhlbHBlcnJlbG9hZGVkLGdpbmNvb2tpc3RvY2tlcjs%3D%21END%21

**Comment by Hringingy** [comment]
There's my save. I think everything matches, but I'm not sure. I can't tell what's supposed to happen when I toggle the switch on, or if I've just been unlucky with buff combos

**Comment by erbkaiser** [comment]
Sorry for not getting back to this yet. The 100% combo is the most complex to debug and I haven't had the time for it yet.

**Comment by Hringingy** [comment]
I think the combo did manage to pull off just recently when I was afk, so I guess was just unlucky earlier. that being said, why does the combo not change settings back to normal when everything is over? I don't want FC to stop buying buildings, using Godzamok, or clicking golden cookies after the combo is over

**Comment by erbkaiser** [comment]
It should reset everything. If it didn't, the combo broke.

**Comment by erbkaiser** [comment]
This was incredibly annoying to fix but it SHOULD be working now.
