### ISSUE TITLE
Autoclick appears to be limited to one click per frame (30 per sec)

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#73]
When I was first playing around with the Autoclick feature, I initially noticed there wasn't any noticable difference in gookie gains between setting the limit to 250 or 1000 clicks per second. After some recent testing, I found out that the Autoclick seems to be capped at 30 clicks per second. Setting the Autoclick to 30 exactly also causes the "Time til completion" timer to tick down in seconds more accurately than at higher values, where the timer ticks very slowly.

**Comment by erbkaiser** [comment]
The game has some nasty traps. Autoclick gets hard capped at 30 IF autoclick is set above 1000, or if the wrong autoclick method is used (directly calling Game.Click instead of Game.ClickCookie() function like FC does).

The trap cap used to be set at 250 which is why FC was limited to that, but in the Cortex bakers update this code was rewritten by Orteil. In my own testing I found it will work for any click speed up to 1000.

**Comment by Hringingy** [comment]
I don't understand. Are you saying it should be possible for FC to click up to 1000 times per second?

**Comment by erbkaiser** [comment]
Yes.

**Comment by Hringingy** [comment]
But why does it not look like 1000 clicks per second is actually happening? Is there something I'm not seeing or am I doing something wrong in the settings?

**Comment by erbkaiser** [comment]
FC doesn't actually click the cookie, it calls the game function that happens when you click. The animation for this is limited to the game update speed. So even though it looks like it maxes out at 1 per frame, it actually performs a lot more cookie clicks.

**Comment by Hringingy** [comment]
When I say "looks like," I'm not talking about the visual animation for clicking on the cookie itself. I'm talking about how quickly my total banked cookies are increasing. There should be a massive difference in how quickly my bank goes up when I set Autoclick to 1000 vs only 30, but there's hardly any change at all.

**Comment by erbkaiser** [comment]
Perhaps your PC or browser is limiting how fast the script can run.
I initially left it at 250 after the CB update but then I experimented and used the graph to confirm the actual upper limit is 1000. This is also confirmed by the code.
If the script is being throttled, you might not be able to actually get it to run that fast, though. Javascript is very inefficient and especially if you run the browser version, it may be capped for performance reasons by methods I cannot possibly control for.

**Comment by Hringingy** [comment]
I'm playing the steam version. After testing with other (less complex) mods, I was able to get a lot more clicks per second on my PC. Maybe you're right in that FC takes a lot of processing power as I know the autobuy at the start of the run can get pretty laggy, but I'm not sure. It's not like the game lags when I set FC Autoclick to high values, it just isn't getting cookies as quickly as it says it should

**Comment by erbkaiser** [comment]
I can't explain why it does not work right for you, unfortunately. Just did another test and with 250 clicks per second I have 574.316 octodec effective CpS, and with 1000 608.088 octodec. 

There is little reason not to set it to the max value, as you'll get the maximum possible clicks that the game allows.

**Comment by Hringingy** [comment]
does the "time til completion" timer not tick seconds down slowly for you when Autoclick is set to high amounts?

**Comment by Hringingy** [comment]
What was your test results with 30 clicks per second?

**Comment by erbkaiser** [comment]
Low.

FC has the built in grapher. It does slow the code down a little, but reports accurate data. I suggest you enable it, then experiment a bit with auto click speeds. Enable the golden switch to prevent any frenzy effects, then let it run for a bit on 30 clicks per second. Then increase. You will see the recorded CpS values go up all the way to 1000 or wherever your PC maxes out.

I did my testing mainly on the Steam version but the web browser will also work.

**Comment by Hringingy** [comment]
It seems like the graph is doing something other than using the average/actual change in cookies over a period of time to do its calculations, or something else is wrong. The graph says my "Base Cps" (I assume this is passive cps without clicking) is 5/6th what the in-game stats say my passive cps is at, possibly because I have Loan 3 active. Even then, when I set Auto click to 1000 per sec, turn off golden cookies, turn off auto frenzy, set Golden Switch to permanently on, and set "GC Clicked 0%" the graph says that my "Effective Cps" (I assume this is supposed to be cps after taking clicking and GC into account) is 318.952 Octillion per sec. However just from visually watching how my banked cookies are changing I can see that it takes longer than a second to even get 100 Octillion cookies.
