### ISSUE TITLE
Auto cast FTHOF casts useless cookies

### ISSUE THREAD

**Issue by valkyriaivan** [erbkaiser/FrozenCookies#74]
I noticed since a few patches away, FTHOF casts when the next cookie is a useless one.
It used to cast Haggler's charm when the next cookie was a bad or useless cookie. I noticed it happening a couple of times. I just tried and it still cast haggler when it's a clot, but useless cookies are still casting FTHOF. Might update tomorrow with a gif.

**Comment by erbkaiser** [comment]
Whatd do you mean by useless?

The normal auto Cast will cast all spells except for Clot and Ruin Cookies.

The combos will only cast 'Sweet', Cookie storm if you still need easter eggs, Click Frenzy, Elder Frenzy, and Building Special

**Comment by erbkaiser** [comment]
I think I see what you mean. I accidentally allowed the normal combo to cast the Cookie Storm Drop and Blabs again.
I'll make those cast HagC again.

**Comment by valkyriaivan** [comment]
That's right, when I said useless cookies I was referring to Blabs, but was late and forgot the name for them haha
As far as I have tested, those that you mentioned are the only times it acts weirdly.

**Comment by valkyriaivan** [comment]
Maybe this can go in a separate issue, but it's related to the auto cast.
Would you like to consider an option for auto casting where it only casts really good cookies? Sometimes using most of my mana to cast a normal frenzy seems usless. Maybe there could be another setting to cast only Click frenzy, building buff, elder frenzy and cursed finger and use hagglers for all the other options including the lesser good cookies.
