### ISSUE TITLE
New autocast option: only cast 'good' spells

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#75]
Maybe this can go in a separate issue, but it's related to the auto cast.
Would you like to consider an option for auto casting where it only casts really good cookies? Sometimes using most of my mana to cast a normal frenzy seems usless. Maybe there could be another setting to cast only Click frenzy, building buff, elder frenzy and cursed finger and use hagglers for all the other options including the lesser good cookies.

_Originally posted by @valkyriaivan in https://github.com/erbkaiser/FrozenCookies/issues/74#issuecomment-1199015724_

**Comment by erbkaiser** [comment]
So basically,  a variant of the existing smart FTHOF that only leaves the click buffs and building specials?

**Comment by valkyriaivan** [comment]
Exactly. I don't want any sugar lump combos or anything. Only use the best cookies and use hagglers for everything else so it can cicle to better spells faster.

**Comment by Hringingy** [comment]
Is that like a single cast version instead of the double cast one that currently exists?

**Comment by valkyriaivan** [comment]
I don't know in depth about the double cast version. But is just a stricter single auto cast where it only casts the best spells, and avoids simple frenzy with haggler charm.
