### ISSUE TITLE
Auto Sugar Frenzy doesn't appear to be working

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#81]
I just ran a FTHOF Doublecast combo, and even though I have "ASF for double cast" enabled, sugar frenzy would not activate. I have around 120 sugar lumps and Sugar Baking Guard enabled, if that's relevant.

**Comment by erbkaiser** [comment]
I forgot to update it last time I changed the combos. Should be working again now.

**Comment by Hringingy** [comment]
Something might be messed up. Sugar Frenzy is now sometimes activating randomly without the combo being triggered
