### ISSUE TITLE
Feature Request: Option to force autobuy research upgrades, ignoring efficiency

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#82]
the current "Grandmapocalypse" blacklist, while convenient for automatically pledging when all Easter/Halloween upgrades have been purchased, disallows the automatic purchasing of Research upgrades, forcing me to manually click on them. Can you add a blacklist option that auto purchases all the research but won't pledge unless "Auto Blacklist" is on and all Seasonal Drops from Wrinklers are purchased?

**Comment by erbkaiser** [comment]
Not going to implement that. The current grandmapocalypse blacklists exists to keep you at your desired point in the GC cycle so it has to allow for manual research selection.

If you want a way to do all the research but never pledge, you can use the **Save Shiny Wrinklers** option, that will simply never buy the pledge. Do not enable the blacklist and just enjoy the grandmapocalypse.

**Comment by Hringingy** [comment]
Oh I didn't know about the save Shiny Wrinklers feature doing that, thanks for the tip!

**Comment by Hringingy** [comment]
I have a couple of other questions then.

1. Why does the "Grandmapocalypse" Blacklist stop the autobuy for Arcane Sugar yet allows the autobuy for Exotic Nuts?

2. Is it intended that during Easter/Halloween, Research will not autobuy even with the Blacklist setting turned off?

**Comment by erbkaiser** [comment]
1. Not my code so I am not 100% certain but I believe the assumption behind the blacklist is that you want to stay at the first stage of the GC to get wrinklers, but not higher as then the chance of wrath cookies becomes much higher.
2. Yes, as wrinklers are required for Halloween cookies and are also a way to get eggs

**Comment by Hringingy** [comment]
1. Arcane sugar does not advance the stage, it's only One Mind, Communal Brainsweep, and Elder Pact. For some reason Exotic Nuts (the research between One Mind and Communal Brainsweep) IS getting autobought, yet Arcane Sugar (the research between Communal Brainsweep and Elder Pact) is NOT getting autobought.
2. Would it not make more sense to allow research to autobuy in that case so wrinklers can actually show up? that's the whole reason I followed your earlier advice to turn blacklist off and preserve Shiny Wrinklers in the first place.


With the way FC is currently set up, I'm not seeing any way of automatically buying research during Easter/Halloween, which was my original intention with the feature request. 

Edit: I just discovered that "Save Shiny Wrinklers" also disables auto purchase of research, but only for One Mind and Communal Brainsweep. I'm so confused :(

**Comment by Hringingy** [comment]
Apparently, it's neither Holidays nor "Save Shiny Wrinklers" at all, it's the efficiency calculation taking into account Golden/Wrath Cookie income and calculating research as negative efficiency. My current workaround for this is to set "GC Clicked" in "Other Options" to 0% so that research gets calculated as positive efficiency and gets bought, but this stops autobuy for all of the GC related upgrades and prevents banking for Lucky's. Can I request an option to force purchase of research and ignore efficiency, so I won't be forced to choose between the two?

**Comment by Hringingy** [comment]
maybe as an option in "Other Upgrades?"
