### ISSUE TITLE
Feature Request: Add Single/Jade slot only mode for Auto-Cyclius

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#85]
I'm currently using Godzamok, Mokalsium, and Muridal as my Pantheon Gods. Correct me if I'm wrong, but I think Muridal is the only one of those 3 that's worth swapping out for Cyclius as the other 2 are too powerful to give up. I would like an option to swap Cyclius only into the Jade slot.

I calculated the time Cyclius is better than Muridal in the Jade Slot to be from ~01:00 to ~11:00 UTC, and the Ruby Slot (Jade Slot with Supreme Intellect) to be from ~01:00 to ~05:00 UTC as well as from ~13:00 to ~17:00 UTC.

**Comment by erbkaiser** [comment]
This would make Cyclius almost useless to automate since it will hardly be able to function. Best left to manual swappning.

**Comment by Hringingy** [comment]
What about utilizing switching in and out Supreme intellect to make the jade slot act like ruby as needed? I don't think Moka should be taken off of Ruby for Cyclius.
