### ISSUE TITLE
Bug: Auto Dragon Petting closes the Krumblor Widget

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#89]
While automatic Dragon Petting is working, each pet action closes the Widget preventing manual use of Krumblor until the upgrade is successfully obtained. This was less of a problem when Auto petting was faster and took less time to get the upgrade.

**Comment by erbkaiser** [comment]
Known issue, can't be fixed without breaking other things. The game doesn't handle widget clicking well so this is the best I can do without breaking other things.

**Comment by Hringingy** [comment]
Can you at least speed Auto petting back up to what it used to be?
