### ISSUE TITLE
Bug: AutoRigidel can misfire and fail to harvest sugar lumps

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#92]
Setting "Autoharvest SL ON + AUTO RIGIDEL" seems to misfire and causes a "botched harvest", failing to get the Sugar Lump. I'm not exactly sure what's causing this.

**Comment by erbkaiser** [comment]
Yeah, this can bug out. It's inherited from upstream where the same happens.
I've tried to tackle it before, but for some reason, Rigidel doesn't always seem to allow the lump to enter ripen stage succesfully.

**Comment by erbkaiser** [comment]
Keeping this open since I am not sure [ef6c8bc](https://github.com/erbkaiser/FrozenCookies/commit/ef6c8bc11c7f0981542887d08b3927fd8afd21dd) is a full fix.

**Comment by Hringingy** [comment]
Maybe it's an issue with autobuy/autosell and building count? It might take a moment for Rigidel to update building count or something. idk

**Comment by erbkaiser** [comment]
It should be impossible for autobuy to kick in before autoRigidel ends.
I've now changed it so it will do another check if the lump is ripe before harvesting - this CAN still fail, but if it does, it will not attempt to harvest and risk losing the lump.
Testing seems to confirm it now works, if it doesn't, I'll reopen this.
