### ISSUE TITLE
Feature Request: Aura Swap option for Autoharvesting Sugar Lumps

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#93]
Similar to how there's and option to switch in Rigidel for harvesting Sugar Lumps sooner, there should also be an option to swap Dragon Auras to Dragon's Curve and Reality Bending when harvesting to further improve the Autoharvest feature.

**Comment by erbkaiser** [comment]
Can you give a bit more info? When should the auras be swapped - directly before harvesting, after harvesting, while ripening etc. -- and when should the 'old' auras be swapped back in?

**Comment by Hringingy** [comment]
I think the auras alter the ripening time based on when the last Sugar Lump was harvested. So probably swap whenever it would change the timer to instantly ripen them similar to Rigidel. As for when to swap back, I would assume it would be if you had Auto Dragon Auras on and then after the Sugar Lump was harvested. Overall, I think the process should be about as quick as the Rigidel swap. 

Just to be clear, I believe it would be worth using BOTH Dragon's Curve AND Reality Bending at the same time for this feature, unlike with Chocolate Egg or Dragon Orbs for example.

**Comment by erbkaiser** [comment]
Code is tested and live. I've implemented it as a new option with and without Reality Bending.

**Comment by Hringingy** [comment]
Doesn't seem to be working right for me. I had to manually set the auras so the lump would properly ripen, then Rigidel got slotted and the lump was left ripe and unharvested (thanks for the failsafe!), Some kinks might need to be worked out with the new feature. I had both Rigidel Slotting and aura swapping on, if that helps.

**Comment by erbkaiser** [comment]
It works in my own testing -- although if auto dragon auras are also active, the dragon aura swaps are so quick that you don't notice them other than by the sound and the loss of 2-4 of the most expensive building.
It will not apply the aura if it's already been set -- although currently, it only checks one slot at the time so if you are running RB in the FIRST slot, it will remove it and then swap that into the second slot which is a waste. I am going to try to work around that but that is for later.

AutoSL with or without Rigidel is required for it to work, as I tied it into the autoSL system to make sure it runs at the right time.

**Comment by Hringingy** [comment]
Is the aura swapping taking into account the change in lump growth time? Both for itself and Rigidel? It wasn't until the manual swap that FC realized the lump was close to maturing and slotted in Rigidel. It seems to not attempt the autoharvest until when It's time to swap in Rigidel rather than factoring in all effects

With all three effects active at the same time, ripening time is reduced down to 18h 57m 26s (roughly around SL maturity time with all ascension upgrades and when there's no pantheon or aura effects).

Also, it seems the failsafe breaks autobuy (and possibly GC clicking) and I had to reload the game to fix things. Is that intentional?
