### ISSUE TITLE
No longer showing time to completion for autobuys

### ISSUE THREAD

**Issue by mikemil1231** [erbkaiser/FrozenCookies#97]
Hello. I love your ad on. 
Just recently I am having a problem where it doesn't show how long until the next autobuy will trigger.
I'm probably doing something wrong, but I was just wondering if there was a setting that might be affecting it.

Looks like this: https://gyazo.com/f6377cd0b24eba902b42f6d3e37fcbaf

Thanks

**Comment by Hringingy** [comment]
Is it because it's now ready to buy or will be ready to buy in less than 1 second?

**Comment by mikemil1231** [comment]
I'm not sure. I was having other issues and ended up whiping the save and cheating to get back to it. Now I'm noticing that the time is showing sometimes, but it's way off. Like it will say 3s to go, except it will stay on 3s for a couple of minutes before going to 2s. Perhaps I screwed with its calculations when I cheated back to where I was?

Thanks for your reply.

**Comment by Hringingy** [comment]
I've noticed the timer tends to be slow and inaccurate when Autoclick is set above ~30/sec. so I'd recommend leaving Autoclick at around that much and setting Autofrenzy as high as you want when you have Godzamok slotted if you want the timer to stay relatively accurate.

**Comment by mikemil1231** [comment]
Yeah I don't actually like the autoclick, it may have been on briefly when I clicked "recommended" at the bottom. Perhaps that screwed with it.

**Comment by mikemil1231** [comment]
I breifly set it to 10 per second. That fixed it! 
Thanks so much Hringingy

**Comment by Hringingy** [comment]
try setting it to 0 if you dont want to use autoclick then

**Comment by erbkaiser** [comment]
Thanks for the assist in providing info @Hringingy.

**Comment by erbkaiser** [comment]
Basically a dupe of #61

**Comment by Hringingy** [comment]
I don't think it's the same thing, but no problem
