### ISSUE TITLE
Missing "Frozen Cookies" options

### ISSUE THREAD

**Issue by VoidLiminal** [erbkaiser/FrozenCookies#98]
I can no longer see the options that should be available via replaced "Info" tab. I tried everything - deleted all mods and connected data, reinstalled the game, had only FC enabled, nothing helped.

**Comment by erbkaiser** [comment]
Browser or Steam? And if browser, live code or beta?

Do you get a pop-up when the game starts that FC is active?

**Comment by VoidLiminal** [comment]
Steam version

I don't see any pop-up unfortunately. It worked all fine just two days ago and then it dissapeared completely.

**Comment by erbkaiser** [comment]
Sounds like the mod simply isn't there. Make sure you're subscribed to it in the Workshop, and if you are and it still doesn't load:
1) Click on Options
2) Click Manage Mods
3) Click Open /mods folder
4) In the Windows explorer window, open /workshop
5) Delete the folder named FrozenCookies
6) Close out of Cookie Clicker and wait about 30 seconds
7) Restart Cookie Clicker

If FC loads now, great! If not, check if it is under Manage Mods and make sure it's Enabled.

If this still fails, download both files from https://github.com/erbkaiser/FrozenCookies/tree/main/Steam/FrozenCookies and put them in a folder called FrozenCookies in the /mods subfolder of the Windows explorer location opened in step 4, then restart CC and make sure the mod is enabled.

**Comment by VoidLiminal** [comment]
I tried everything you advised, and it still refuses to load, I am absolutely puzzled by this. Reinstalled it multiple times, deleted all data, even the whole Cookie Clicker Steam folder to no avail.

The files are exactly where they are supposed to, mod is enabled via game itself and there are still no mod options to access, just makes no sense to me.

**Comment by Trisstrender** [comment]
Heads-up, after manual installation and PC restart everything is working again. Thank you for all your help, hopefully this won't happen again.

**Comment by Trisstrender** [comment]
Heads up, after manual installation and PC restart everything is working again. Thank you for all your help, hopefully this won't happen again.

**Comment by VoidLiminal** [comment]
Heads up, after manual installation and PC restart everything is working again. Thank you for all your help, hopefully this won't happen again.

One more question though - will the mod update itself automatically even when manually installed?

**Comment by erbkaiser** [comment]
Great!

Yes, the mod will always run the latest live version even if manually installed. The Steam mod only exists to load the runcode from online.
