### ISSUE TITLE
Calculate time to swap in Dragon's Curve to shorten SL ripe age

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#99]
you can't do a quick n' dirty solution of manually calculating the minimum amount of time saved by Dragon's curve by itself (I assume this could be done by just adding everything other than auras up and then calculating time saved based on that), using that as a fixed value, and then just adding ~58 minutes to that if auto Rigidel is also on at the same time? it might not save an optimum amount of time when you don't have all upgrades but it'll at least save _some_ amount of extra time. Rigidel won't save exactly 1 hour either when Dragon's Curve or more is active, particularly if I have those auras on by default rather than using autoswap as that's what I did before requesting this feature.

_Originally posted by @Hringingy in https://github.com/erbkaiser/FrozenCookies/issues/96#issuecomment-1242462318_

**Comment by Hringingy** [comment]
yeah I meant ~56 minutes for Rigi (forgot to calculate Reality Bending)

**Comment by Hringingy** [comment]
Like not so much calcluating the time within FC, but rather just using some arbitrary number for Dragon's Curve when active

**Comment by erbkaiser** [comment]
That would run counter to the mod design. Unless I can find a way to calculate the exact time it shortens, I won't implement this.

**Comment by Hringingy** [comment]
another Idea for a quick n' dirty solution: swap the aura(s) in whenever the Lump is Mature, and swap the auras out when the Lump is harvested.

Or would that also run counter to mod design?
